### PR TITLE
fix: global eq delete matching should apply to only strictly older files, and fix partition scoped matching to consider spec id

### LINKED ISSUE #1759: Equality Delete Matching over applies global equality deletes
### Apache Iceberg Rust version

0.6.0 (latest version)

### Describe the bug

Right now it looks like we match global eq deletes if they are greater than or equal to the the data file sequence number but that's incorrect. Unless I'm missing something in the assumptions of the rust implementation, equality deletes must only be applied if they are strictly higher sequence numbered. Otherwise the reader currently looks like it'll apply those equality deletes to data files which are at the same sequence number which isn't quite correct (again could be missing something)

### To Reproduce

_No response_

### Expected behavior

_No response_

### Willingness to contribute

None

### PR DESCRIPTION
**Pull request by amogh-jahagirdar**
## Which issue does this PR close?

- Closes #1759.

## What changes are included in this PR?

This changes scan planning of equality deletes so that: 
1. we only match against eq deletes which are strictly older than the data file. Right now it looks like we incorrectly over-apply based on the seq number for global equality deletes.

2. Partition scoped deletes (both equality and position) are compared correctly by also factoring in the spec ID. It's not quite enough to compare just off the tuple, we should also compare based off the spec ID as well.

## Are these changes tested?

Added unit tests which are scoped to testing delete index matching logic.

If tests are not included in your PR, please explain why (for example, are they covered by existing tests)?
-->

### CODE REVIEW

File: crates/iceberg/src/delete_file_index.rs [hunk 1]
```diff
@@ -169,10 +169,10 @@ impl PopulatedDeleteFileIndex {
 
         self.global_deletes
             .iter()
-            // filter that returns true if the provided delete file's sequence number is **greater than or equal to** `seq_num`
+            // filter that returns true if the provided delete file's sequence number is **greater than** `seq_num`
```
Comment (amogh-jahagirdar) [inline crates/iceberg/src/delete_file_index.rs:173]: I could just be missing something in the implementation, but right now seems like we're over applying in a way that would technically be incorrect. If a snapshot has some added data files and an equality delete, the equality deletes should only be applied to older seq numbers. We do this correctly for partition scoped eq deletes below, but for some reason the global equality delete matching is different;  the seq number criteria for eq deletes applies regardless of scope of the delete.

Comment (amogh-jahagirdar) [reply crates/iceberg/src/delete_file_index.rs:173]: I noticed this when I was working on some optimizations for equality delete matching (eliminating eq deletes to apply based on bounds)

Comment (kevinjqliu) [reply crates/iceberg/src/delete_file_index.rs:173]: Thanks for catching this. I think "greater than" is correct here. The `global_deletes` variable is used for gathering all the eq delete files for an unpartitioned table, but the same logic should still apply.

Looking at past commits, i did find this was previously discussed [here](https://github.com/apache/iceberg-rust/pull/1077#discussion_r2000091436)

Also from https://iceberg.apache.org/spec/#scan-planning
Screenshot 2025-10-18 at 5 57 03 PM
This implies that we should not apply eq delete files that have equivalent sequence number

Comment (amogh-jahagirdar) [reply crates/iceberg/src/delete_file_index.rs:173]: Yeah, thanks for finding that github thread, looks like the confusion was what global_deletes meant, but really it's global equality deletes. Regardless any equality delete must be applied for files strictly older. I also fixed some of the partition scoped delete matching logic because it's technically possible to have tuples match but the spec IDs don't match; currently we only go off the tuple which isn't quite correct for matching as well.

File: crates/iceberg/src/delete_file_index.rs [hunk 2]
```diff
@@ -201,10 +203,282 @@ impl PopulatedDeleteFileIndex {
                     seq_num
                         .map(|seq_num| delete.manifest_entry.sequence_number() >= Some(seq_num))
                         .unwrap_or_else(|| true)
+                        && data_file.partition_spec_id == delete.partition_spec_id
```
Comment (kevinjqliu) [inline crates/iceberg/src/delete_file_index.rs:206]: Image

👍 
partition value match is handled by `self.pos_deletes_by_partition.get(data_file.partition()) `

File: crates/iceberg/src/delete_file_index.rs
Comment (kevinjqliu) [inline crates/iceberg/src/delete_file_index.rs]:
```suggestion
    ///    it is added to the `global_equality_deletes` vector
```
s/global_deletes/global_equality_deletes

File: crates/iceberg/src/delete_file_index.rs [hunk 3]
```diff
@@ -201,10 +203,282 @@ impl PopulatedDeleteFileIndex {
...
+
+    fn build_unpartitioned_pos_delete() -> DataFile {
+        build_partitioned_pos_delete(&Struct::empty(), 0)
+    }
+
+    fn build_partitioned_pos_delete(partition: &Struct, spec_id: i32) -> DataFile {
+        DataFileBuilder::default()
+            .file_path(format!("{}-dv.puffin", Uuid::new_v4()))
+            .file_format(DataFileFormat::Puffin)
+            .content(DataContentType::PositionDeletes)
```
Comment (kevinjqliu) [inline crates/iceberg/src/delete_file_index.rs]: nit: should we use position-based delete files instead of puffin (dv) since we're testing for v2 table behaviors here?

File: crates/iceberg/src/delete_file_index.rs [hunk 4]
```diff
@@ -201,10 +203,282 @@ impl PopulatedDeleteFileIndex {
...
+    };
+
+    #[test]
+    fn test_delete_file_index_unpartitioned() {
+        let deletes: Vec<ManifestEntry> = vec![
+            build_added_manifest_entry(4, &build_unpartitioned_eq_delete()),
+            build_added_manifest_entry(6, &build_unpartitioned_eq_delete()),
+            build_added_manifest_entry(5, &build_unpartitioned_pos_delete()),
+            build_added_manifest_entry(6, &build_unpartitioned_pos_delete()),
+        ];
```
Comment (kevinjqliu) [inline crates/iceberg/src/delete_file_index.rs:232]:
```suggestion
            build_added_manifest_entry(4, &build_unpartitioned_eq_delete()),
            build_added_manifest_entry(5, &build_unpartitioned_pos_delete()),
            build_added_manifest_entry(6, &build_unpartitioned_eq_delete()),
            build_added_manifest_entry(6, &build_unpartitioned_pos_delete()),
        ];
```

nit for readability, feel free to ignore

Comment (kevinjqliu) [reply crates/iceberg/src/delete_file_index.rs:232]: oh haha, the first 2 being equality deletes is used by 

`delete_file_paths[..2]`

**Review by kevinjqliu — APPROVED** [review]
LGTM! 

Thanks for adding the tests

File: crates/iceberg/src/delete_file_index.rs (hunk 4 above)
Comment (amogh-jahagirdar) [reply crates/iceberg/src/delete_file_index.rs:232]: Yeah exactly, it's to exercise the path that prompted this fix

File: crates/iceberg/src/delete_file_index.rs (hunk 3 above)
Comment (amogh-jahagirdar) [reply crates/iceberg/src/delete_file_index.rs]: Good point, yeah. We'll want to add the DV validation once the DV matching is added (matching against the actual data file location)

File: crates/iceberg/src/delete_file_index.rs (hunk 2 above)
Comment (amogh-jahagirdar) [reply crates/iceberg/src/delete_file_index.rs:206]: Exactly. We could also define a key which is tupled off the <spec ID, partition value> pair in the map (this is what the java implementation does).

Comment (kevinjqliu) [reply crates/iceberg/src/delete_file_index.rs:206]: lets see if we can refactor this in a follow up PR and keep the changes here straightforward :)
