### PR TITLE
fix: build_fallback_field_id_map produces incorrect column indices for schemas with nested types

### LINKED ISSUE #2306: bug: build_fallback_field_id_map produces incorrect column indices for schemas with nested types
### Describe the bug

`build_fallback_field_id_map` maps Iceberg field IDs to wrong Parquet leaf column indices when the schema contains nested types (struct, list, map). This causes predicate evaluation to crash on migrated Parquet files (files without embedded field IDs).

**Error:**
"Leave column id in predicates isn't a root column in Parquet schema"

This affects migrated tables where Parquet files were written by Spark/Hive without Iceberg field IDs, then imported via `add_files` or `importSparkTable()`.

#### How fallback field IDs work

When a Parquet file lacks embedded field IDs, iceberg-rust assigns position-based fallback IDs. Two functions must agree on the mapping:

1. `add_fallback_field_ids_to_arrow_schema` — assigns field IDs 1, 2, 3... to **top-level** Arrow schema fields
2. `build_fallback_field_id_map` — maps those field IDs to Parquet **leaf** column indices for predicate evaluation

#### What goes wrong

`build_fallback_field_id_map` iterates over `parquet_schema.columns()` (leaf columns) instead of top-level fields. Nested types expand into multiple leaves,
causing the mapping to diverge from the Arrow schema's field IDs.

**Example:** `name: string, address: struct(street: string, city: string), id: int`

| | Arrow top-level fields | Parquet leaf columns |
|---|---|---|
| Fields | name, address, id | name, street, city, id |
| Assigned field IDs | 1, 2, 3 | 1, 2, 3, 4 (bug) |

When a predicate references `id` (field_id=3 from Arrow), the column map returns leaf index 2 (`city`, inside the `address` group). `PredicateConverter::bound_reference` then calls `get_column_root(2).is_group()` → `true` → error.

### How Iceberg Java handles this

Java's [`ParquetSchemaUtil.addFallbackIds()`](https://github.com/apache/iceberg/blob/main/parquet/src/main/java/org/apache/iceberg/parquet/ParquetSchemaUtil.java#L174-L184) iterates **top-level fields**, not leaf columns:

```java
public static MessageType addFallbackIds(MessageType fileSchema) {
    MessageTypeBuilder builder = org.apache.parquet.schema.Types.buildMessage();
    int ordinal = 1;
    for (Type type : fileSchema.getFields()) {
        builder.addField(type.withId(ordinal));
        ordinal += 1;
    }
    return builder.named(fileSchema.getName());
}
```

Additionally, Java's https://github.com/apache/iceberg/blob/main/parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java gracefully handles nested types — predicates on nested columns return ROWS_MIGHT_MATCH instead of crashing.

### Proposed Fix

Change `build_fallback_field_id_map` to iterate over `parquet_schema.root_schema().get_fields()`` (top-level fields) instead of `parquet_schema.columns()`` (leaf columns).
 For each top-level field:
- If primitive: map `ordinal` → `leaf_column_index`
- If group (struct/list/map): skip the mapping, advance the leaf counter past all leaves in that group

This makes `build_fallback_field_id_map` consistent with `add_fallback_field_ids_to_arrow_schema`, which already correctly iterates top-level Arrow fields.

`PredicateConverter::bound_reference` already validates that the resolved column is a root column and rejects groups, so no changes are needed there.

Files to modify

1. `crates/iceberg/src/arrow/reader.rs — build_fallback_field_id_map`

Related

- https://github.com/apache/datafusion-comet/issues/3860: Downstream issue in Comet

### PR DESCRIPTION
**Pull request by mbutrovich**
## Which issue does this PR close?

- Closes #2306.
- Downstream issue: https://github.com/apache/datafusion-comet/issues/3860

## What changes are included in this PR?                  

`build_fallback_field_id_map` iterated over Parquet leaf columns instead of top-level fields when building the field ID to column index mapping for migrated files (no embedded field IDs). When nested types (struct, list, map) precede a primitive column, they expand into multiple leaves, causing the mapping to diverge from `add_fallback_field_ids_to_arrow_schema` which correctly assigns ordinal IDs to top-level Arrow fields. This made predicates on columns after nested types resolve to a leaf inside the group, crashing with "Leaf column `id` in predicates isn't a root column in Parquet schema".

The fix iterates `root_schema().get_fields()` directly, assigning ordinal IDs only to top-level fields. For non-primitive fields (struct/list/map), it uses `get_column_root_idx` to advance past their leaf columns. This mirrors iceberg-java's `ParquetSchemaUtil.addFallbackIds()`, which iterates `fileSchema.getFields()` assigning ordinal IDs to top-level fields.

Also renames "Leave column" to "Leaf column" in error messages.

## Are these changes tested?

- An integration test (`test_predicate_on_migrated_file_with_nested_types`) writes a Parquet file without field IDs containing struct, list, and map columns before an `id` column, then reads with a predicate on `id`. This reproduces the exact crash before the fix. Test data is constructed with `serde_arrow` for readability.

- [Apache DataFusion Comet](https://github.com/apache/datafusion-comet) used the repro test in
[apache/datafusion-comet#3860](https://github.com/apache/datafusion-comet/issues/3860) and it passes with this change:
https://github.com/apache/datafusion-comet/pull/3872

### CODE REVIEW

File: crates/iceberg/src/arrow/reader.rs [hunk 1]
```diff
@@ -1111,14 +1111,24 @@ fn build_field_id_map(parquet_schema: &SchemaDescriptor) -> Result<Option<HashMa
...
 /// Build a fallback field ID map for Parquet files without embedded field IDs.
-/// Position-based (1, 2, 3, ...) for compatibility with iceberg-java migrations.
+///
+/// Must use top-level field positions (not leaf column positions) to stay consistent
+/// with `add_fallback_field_ids_to_arrow_schema`, which assigns ordinal IDs to
+/// top-level Arrow fields. Using leaf positions instead would produce wrong indices
+/// when nested types (struct/list/map) expand into multiple leaf columns.
+///
+/// Matches iceberg-java's ParquetSchemaUtil.addFallbackIds().
 fn build_fallback_field_id_map(parquet_schema: &SchemaDescriptor) -> HashMap<i32, usize> {
```
Comment (blackmwk) [inline crates/iceberg/src/arrow/reader.rs:1134]: I think this is not mapping java's behavior. How about making it more like java:
```rut
parquet_schema.root_schema().fields().zip_with_index(...)
```

Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs:1134]: I'll take a look, thanks for the feedback @blackmwk!

Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs:1134]: Updated to iterate `root_schema().get_fields()` directly, mirroring Java's `fileSchema.getFields()` loop. For primitives we map ordinal -> leaf index; for groups we advance the leaf counter using `get_column_root_idx` to skip past their leaves.

We can't do an exact 1:1 with Java because Java's `addFallbackIds` just stamps IDs onto the Parquet `MessageType` and lets the Parquet reader handle column resolution later. Here we need to produce a `field_id -> leaf_column_index` map eagerly since arrow-rs needs leaf indices for projection. So the structure mirrors Java but the output is what our reader pipeline consumes.

File: crates/iceberg/src/arrow/reader.rs [hunk 2]
```diff
@@ -4667,4 +4691,268 @@ message schema {
...
+                    .copied()
+            })
+            .collect();
+        assert_eq!(ids, vec![2, 3]);
+    }
+
+    /// Regression for <https://github.com/apache/iceberg-rust/issues/2306>:
+    /// predicate on a column after a struct in a migrated file (no field IDs).
+    #[tokio::test]
+    async fn test_predicate_on_migrated_file_with_struct() {
```
Comment (blackmwk) [inline crates/iceberg/src/arrow/reader.rs]: How about merging these three into one test case? The motivation is to see test the correctness in a more complex schema.

Comment (blackmwk) [reply crates/iceberg/src/arrow/reader.rs]: Also, it would be nice if we could use sth like https://docs.rs/serde_arrow/latest/serde_arrow/index.html to make the tests more readable.

**Review by blackmwk — COMMENTED** [review]
Thanks @mbutrovich for this fix! Generally LGTM!

File: crates/iceberg/src/arrow/reader.rs (hunk 1 above)
Comment (blackmwk) [reply crates/iceberg/src/arrow/reader.rs:1134]: Got it, thanks for the explaination!  Hopefully we could refactor it someday to make the logic more similar to java.

File: crates/iceberg/src/arrow/reader.rs (hunk 2 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: Sounds good, thanks @blackmwk!

**Comment by mbutrovich** [comment]
Most recent changes:
- **`crates/iceberg/Cargo.toml`** — added `serde_arrow = { version = "0.14", features = ["arrow-58"] }` dev-dependency
- **`crates/iceberg/src/arrow/reader.rs`** — replaced three separate tests (`test_predicate_on_migrated_file_with_{struct,list,map}`) and the shared helper with one `test_predicate_on_migrated_file_with_nested_types` that:
  - Uses `serde_arrow` with `Serialize`/`Deserialize` structs for readable data construction
  - Tests a schema with all three nested types (struct, list, map) before the `id` column

File: crates/iceberg/src/arrow/reader.rs [hunk 3]
```diff
@@ -1111,14 +1111,33 @@ fn build_field_id_map(parquet_schema: &SchemaDescriptor) -> Result<Option<HashMa
...
+            column_map.insert(field_id, leaf_idx);
+            leaf_idx += 1;
+        } else {
+            // Advance past all leaves in this group. Count them by checking
+            // how many subsequent leaves share this root index.
+            while leaf_idx < parquet_schema.num_columns()
+                && parquet_schema.get_column_root_idx(leaf_idx) == top_pos
+            {
+                leaf_idx += 1;
+            }
```
Comment (c-thiel) [inline crates/iceberg/src/arrow/reader.rs]: Just a nit, but should we extract a recursive `leaf_count(&ParquetType) -> usize` and writing the loop as:
```rust
if field.is_primitive() {
    column_map.insert(field_id, leaf_idx);
}
leaf_idx += leaf_count(field);
```
Decouples the map-building from parquet_schema's flat leaf layout. Then we would not need to rely on num_columns(), get_column_root_idx(), and the DFS-ordering invariant being kept in lockstep with a cursor.

File: crates/iceberg/src/arrow/reader.rs [hunk 4]
```diff
@@ -1111,14 +1111,33 @@ fn build_field_id_map(parquet_schema: &SchemaDescriptor) -> Result<Option<HashMa
...
-/// Position-based (1, 2, 3, ...) for compatibility with iceberg-java migrations.
+///
+/// Must use top-level field positions (not leaf column positions) to stay consistent
+/// with `add_fallback_field_ids_to_arrow_schema`, which assigns ordinal IDs to
+/// top-level Arrow fields. Using leaf positions instead would produce wrong indices
+/// when nested types (struct/list/map) expand into multiple leaf columns.
+///
+/// Mirrors iceberg-java's ParquetSchemaUtil.addFallbackIds() which iterates
+/// fileSchema.getFields() assigning ordinal IDs to top-level fields.
 fn build_fallback_field_id_map(parquet_schema: &SchemaDescriptor) -> HashMap<i32, usize> {
```
Comment (c-thiel) [inline crates/iceberg/src/arrow/reader.rs:1134]: I think we should add a doc here making the contract explicit: "entries only for primitive top-level fields."
Checked the consumers (PredicateConverter, RowGroupMetricsEvaluator::stats_for_field_id, get_row_selection_for_filter_predicate) — all resolve field ids to primitive leaves, so primitive-only seems exactly right. As discussed before this diverges slightly from Java's ParquetSchemaUtil.addFallbackIds, which attaches an ordinal id to every top-level field (not just primitives) — but Java's downstream lookups only resolve primitives anyway, so observable behavior should match.

**Comment by mbutrovich** [comment]
Thanks for the feedback @c-thiel! I will take a look at your comments in detail a little later today. Appreciate the :eyes: on the PR!

**Review by blackmwk — APPROVED** [review]
Thanks @mbutrovich for this fix!
