### PR TITLE
refine: refine manifest_evaluator to reject not explicitly

### LINKED ISSUE #1355: Partition file filtering logic is incorrect for logical `not()` function
### Apache Iceberg Rust version

0.4.0 (latest version)

### Describe the bug

Consider the following example table partition file:

| `id`  | `count` |
| ------------- | ------------- |
| "a"  | 3  |
| "b"  | 2  |
| "c"  | 5  |
| "d"  | 7  |
| "e"  | 5  |

This partition file will have statistics:

| statistic  | column | value |
| ------------- | ------------- | --- |
| lower_bound  | `count` | 2 |
| upper_bound  | `count` | 7 |

If I perform a query with predicate `count >= 5`, this partition must be included.

If I perform a query with predicate `not(count >= 5)`, this partition *must still be included*.

The logic in [manifest_evaluator.rs](https://github.com/apache/iceberg-rust/blob/50de31a5ef7518aeefad88ed9d815cd24ca962b8/crates/iceberg/src/expr/visitors/manifest_evaluator.rs#L70) is currently 2-values, with options `ROWS_MIGHT_MATCH` and `ROWS_CANNOT_MATCH`. But then the only correct behavior for `not` would be

```rs
    fn not(&mut self, inner: bool) -> crate::Result<bool> {
      ROWS_MIGHT_MATCH
    }
```

The tests need to be expanded in order to catch this logical error, and a 3-value logic with (`MUST_MATCH`, `MIGHT_MATCH`, `CANNOT_MATCH`) values probably needs to be adopted to correctly handle all of these cases.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Willingness to contribute

I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by ZENOTME**
## Which issue does this PR close?

Closes #1355

## What changes are included in this PR?

As discuss in https://github.com/apache/iceberg-rust/issues/1355#issuecomment-2982417539 , this pr change to:
- return unexpect error for not in ManifestFilterVisitor to avoid confusion 
- rename the new and comment to declare the invariant explicitly

### CODE REVIEW

**Comment by ZENOTME** [comment]
cc @liurenjie1024 @Fokko @kevinjqliu @Xuanwo @sdd

File: crates/iceberg/src/expr/visitors/manifest_evaluator.rs [hunk 1]
```diff
@@ -33,7 +33,10 @@ pub(crate) struct ManifestEvaluator {
 }
 
 impl ManifestEvaluator {
-    pub(crate) fn new(partition_filter: BoundPredicate) -> Self {
+    /// `ManifestEvaluator` is not support to evaluate predicate with `not` operator.
+    /// This function requires that caller pass the predicate has been rewritten. Otherwise,
+    /// it will return unexpected error when evaluating the predicate.
+    pub(crate) fn new_without_rewrite_not(partition_filter: BoundPredicate) -> Self {
```
Comment (liurenjie1024) [inline crates/iceberg/src/expr/visitors/manifest_evaluator.rs]: Instead of renaming constructor, how about add a new builder function like following:
```rust
pub(crate) fn with_rewrite_not(self, rewrite: bool) {
...
}
```

Also we should add some tests to cover rewriting not

File: crates/iceberg/src/expr/visitors/manifest_evaluator.rs [hunk 2]
```diff
@@ -23,6 +23,43 @@ use crate::expr::{BoundPredicate, BoundReference};
...
+            partition_filter,
+            rewrite_not: false,
+        }
+    }
+
+    /// Enables NOT rewriting optimization for the partition filter.
+    /// When enabled, the builder will apply NOT elimination to simplify the predicate
+    /// before creating the evaluator.
+    #[allow(unused)]
+    pub(crate) fn with_rewrite(mut self, rewrite_not: bool) -> Self {
```
Comment (liurenjie1024) [inline crates/iceberg/src/expr/visitors/manifest_evaluator.rs]:
```suggestion
    pub(crate) fn with_rewrite_not(mut self, rewrite_not: bool) -> Self {
```

**Comment by Fokko** [comment]
Nice one @ZENOTME Thanks for working on this 🙌
