### PR TITLE
Fix day timestamp micro

### LINKED ISSUE #311: Bug: `fn day_timestamp_micro` produces wrong results
### Description:
`fn day_timestamp_micro` ([source](https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/transform/temporal.rs#L167)) seems to produce the wrong result which is off-by-one due to rounding errors.
Also the implementation does not align with the [Java ](https://github.com/apache/iceberg/blob/d350c9b8c995a2953aa8b80a0a1fc7cadc4dd16a/api/src/main/java/org/apache/iceberg/util/DateTimeUtil.java#L174-L184C7)implementation, which handles the conversion slightly different.

An example of the wrong output can be seen in the [test](https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/transform/temporal.rs#L587):
`-115200000000` evaluates to `1969-12-30T16:00:00Z` which should be days -2 (since epoch) and not -1.

### Proposal:
Align Rust with Java implementation.
I already have a prototype, due to working on #264, so I will implement the fix in a different PR - so it can be verified more easily.

### PR DESCRIPTION
**Pull request by marvinlanhenke**
### Which issue does this PR close?
Closes #311

### Rationale for this change
Align timestamp conversion with Java implementation. Unblock #309

### What changes are included in this PR?
- changed `fn day_timestamp_micro`

### Are these changes tested?
Yes. Unit tests are included.

### CODE REVIEW

File: crates/iceberg/src/transform/temporal.rs [hunk 1]
```diff
@@ -175,7 +200,7 @@ impl TransformFunction for Day {
                 .as_any()
                 .downcast_ref::<TimestampMicrosecondArray>()
                 .unwrap()
-                .unary(|v| -> i32 { Self::day_timestamp_micro(v) }),
+                .unary(|v| -> i32 { Self::day_timestamp_micro(v).unwrap() }),
```
Comment (marvinlanhenke) [inline crates/iceberg/src/transform/temporal.rs:203]: @liurenjie1024 
can we handle the unwrap() properly, haven't found a way yet. But perhaps you have an idea?

**Comment by marvinlanhenke** [comment]
@liurenjie1024 
as discussed in #311 PTAL.

I also left a comment in transform - I haven't found a better way yet, to handle the `unwrap()` here. Perhaps you have an idea?

**Review by liurenjie1024 — APPROVED** [review]
Thanks @marvinlanhenke for the fix!
