### PR TITLE
fix(rest): Filter sensitive headers from error logs (#2117)

### LINKED ISSUE #2117: Sensitive Header Leaks in Error Responses
### Apache Iceberg Rust version

0.6.0 (latest version)

### Describe the bug

Following the introduction of header logging in #1129, error messages now include a full dump of response headers to assist with debugging.

While helpful for troubleshooting, this current implementation poses a security risk. In environments utilizing specific proxies or middleware, the error logs capture and display sensitive headers, such as Set-Cookie, which contain authentication tokens and session information. 

The following is an example log from Arroyo (using iceberg-rs)  that demonstrates the issue with `Unexpected` error variant.

```json
{
  "arroyo_service": "worker",
  "level": "ERROR",
  "fields": {
    "message": "panicked at crates/arroyo-connectors/.../two_phase_committer.rs:175:14: committer initialized: ConnectorError { 
      domain: External, 
      retry: NoRetry, 
      error: \"Unexpected, context: { 
        status: 404 Not Found, 
        headers: {
          \"date\": \"Sat, 31 Jan 2026 09:22:55 GMT\",
          \"content-type\": \"application/json\",
          \"server\": \"cloudflare\",
          \"set-cookie\": \"CF_Authorization=[REDACTED_SENSITIVE_TOKEN]; Path=/; Secure;\", 
          \"x-request-id\": \"3363c133-a05f-493d-a3ab-8b75814c8c3d\"
        }, 
        json: {\"error\":{\"message\":\"Warehouse not found\",\"type\":\"WarehouseNotFound\",\"code\":404}} 
      } => Received response with unexpected status code\", 
      source: None 
    }"
  },
  "pipeline_id": "b00f0dd0..."
}
```

https://github.com/apache/iceberg-rust/blob/b41ecb455a4cee716864a4949b20dc229d91b844/crates/catalog/rest/src/client.rs#L281-L299

### To Reproduce

_No response_

### Expected behavior

Sensitive headers should be redacted or excluded from error strings by default. Users should have the ability to debug headers without exposing PII (Personally Identifiable Information) or credentials in logs.

Suggested Fixes
- Redaction List: Implement a default deny list for common sensitive headers (e.g., `Set-Cookie`, `Authorization`, `Proxy-Authorization`).
- Toggleable Logging: Allow users to opt in to full header logging via a configuration flag, keeping it disabled by default for safety.

### Willingness to contribute

I would be willing to contribute a fix for this bug with guidance from the Iceberg community

### PR DESCRIPTION
**Pull request by cmackenzie1**
## Which issue does this PR close?

- Closes #2117

## What changes are included in this PR?

Sensitive headers like Set-Cookie, Authorization, and Cookie were being included in error messages, potentially exposing authentication tokens and session information in logs.

This change replaces sensitive headers with `[REDACTED]` from error context rather than logging their values, preventing credential leakage.

This option can be disabled using `REST_CATALOG_PROP_DISABLE_HEADER_REDACTION=true`

## Are these changes tested?

Covered by unit tests.

### CODE REVIEW

File: crates/catalog/rest/src/client.rs [hunk 1]
```diff
@@ -278,14 +278,40 @@ pub(crate) async fn deserialize_catalog_response<R: DeserializeOwned>(
...
+}
+
+/// Filters out sensitive headers and returns a debug-formatted string.
+fn format_headers_redacted(headers: &HeaderMap) -> String {
+    let filtered: HashMap<&str, &str> = headers
+        .iter()
+        .filter(|(name, _)| !is_sensitive_header(name.as_str()))
+        .filter_map(|(name, value)| value.to_str().ok().map(|v| (name.as_str(), v)))
+        .collect();
+    format!("{filtered:?}")
```
Comment (blackmwk) [inline crates/catalog/rest/src/client.rs]: When we say redacting sensitive header, I think we replace actually content with things like `xxxx` rather than removing them?

Comment (blackmwk) [reply crates/catalog/rest/src/client.rs]: The reason we want to keep them rather than removing them directly is that if maybe confusing when missing these headers when debugging. Also, I would prefer to add a config to disable the redaction. We could redact these header by default, but we should allow user to disable it.

Comment (cmackenzie1) [reply crates/catalog/rest/src/client.rs]: Thanks for the feedback @blackmwk! Updated to redact instead of filter using `[REDACTED]` as a value and made it configurable.

File: crates/catalog/rest/src/client.rs [hunk 2]
```diff
@@ -278,14 +287,64 @@ pub(crate) async fn deserialize_catalog_response<R: DeserializeOwned>(
...
+fn is_sensitive_header(name: &str) -> bool {
+    let name_lower = name.to_lowercase();
+    SENSITIVE_HEADERS.iter().any(|h| name_lower == *h)
+}
+
+/// Redacts sensitive headers and returns a debug-formatted string.
+///
+/// If `disable_redaction` is true, returns all headers without redaction.
+/// Otherwise, replaces sensitive header values with "[REDACTED]".
+fn format_headers_redacted(headers: &HeaderMap, disable_redaction: bool) -> String {
```
Comment (blackmwk) [inline crates/catalog/rest/src/client.rs:310]:
```suggestion
fn format_headers(headers: &HeaderMap, disable_redaction: bool) -> String {
```

**Review by blackmwk — APPROVED** [review]
The method name is a little odd, but it's an internal method, so I think it's fine to go. Thanks @cmackenzie1 for this pr!
