### PR TITLE
fix: MemoryCatalog to return absolute NamespaceIdents

### LINKED ISSUE #1969: MemoryCatalog returns relative namespace identifiers rather than absolute
### Apache Iceberg Rust version

None

### Describe the bug

Other implementations of `list_namespace(parent)` return absolute namespace identifiers. For example, if there is a namespace `b` under `a`, `list_namespace("a")` should return `NamespaceIdent::from_strs(vec!["a", "b"])`. This is documented in the [REST OpenAPI spec](https://github.com/apache/iceberg/blob/4632f3133efbf6b8232ed9526de7142fd50e1aa6/open-api/rest-catalog-open-api.yaml#L251), the [Java implementation](https://iceberg.apache.org/javadoc/1.10.1/org/apache/iceberg/catalog/SupportsNamespaces.html#loadNamespaceMetadata(org.apache.iceberg.catalog.Namespace)) and, in this repo, in [SqlCatalog](https://github.com/apache/iceberg-rust/blob/99ca196a7a81343ac35d993d9db2ec59c626f389/crates/catalog/sql/src/catalog.rs#L1396).

MemoryCatalog returns relative identifiers, as can be seen [here](https://github.com/apache/iceberg-rust/blob/99ca196a7a81343ac35d993d9db2ec59c626f389/crates/iceberg/src/catalog/memory/catalog.rs#L597). To make MemoryCatalog mimick real implementations better, the behaviour should be fixed.

### To Reproduce

Current behaviour is demonstrated in a [MemoryCatalog unit test](https://github.com/apache/iceberg-rust/blob/99ca196a7a81343ac35d993d9db2ec59c626f389/crates/iceberg/src/catalog/memory/catalog.rs#L597).

### Expected behavior

Desired behaviour is demonstrated in the matching [SqlCatalog unit test](https://github.com/apache/iceberg-rust/blob/99ca196a7a81343ac35d993d9db2ec59c626f389/crates/catalog/sql/src/catalog.rs#L1396).

### Willingness to contribute

I can contribute a fix for this bug independently

### PR DESCRIPTION
**Pull request by eickler**
## Which issue does this PR close?

- Closes #1969.

## What changes are included in this PR?

The change makes `list_namespaces(parent)` return an absolute namespace identifier instead of a relative.

## Are these changes tested?

The associated unit tests are updated with the same behaviour as SqlCatalog.

### CODE REVIEW

**Comment by eickler** [comment]
Note: I am currently trying to fix the Datafusion integration to work with nested namespaces. As part of unit testing using MemoryCatalog, I encountered this small issue. I read in the discussions that you prefer smaller PRs over larger ones, so I took the liberty of submitting it like this.

File: crates/iceberg/src/catalog/memory/catalog.rs [hunk 1]
```diff
@@ -163,7 +163,11 @@ impl Catalog for MemoryCatalog {
                 let namespaces = root_namespace_state
                     .list_namespaces_under(parent_namespace_ident)?
                     .into_iter()
-                    .map(|name| NamespaceIdent::new(name.to_string()))
+                    .map(|name| {
+                        let mut names = parent_namespace_ident.iter().cloned().collect::<Vec<_>>();
+                        names.push(name.to_string());
+                        NamespaceIdent::from_vec(names).unwrap()
```
Comment (CTTY) [inline crates/iceberg/src/catalog/memory/catalog.rs]: We should propgate the error rather than unwrapping it here

**Review by CTTY — COMMENTED** [review]
Thanks for the fix! Just a minor comment

File: crates/iceberg/src/catalog/memory/catalog.rs (hunk 1 above)
Comment (eickler) [reply crates/iceberg/src/catalog/memory/catalog.rs]: Ah sorry, I have only started with Rust. I thought unwrap() would be reasonable here since `names` is guaranteed to have at least one element and the result can only be Err if `names` has no elements.

I could terminate on the first error and return the error. Is that better?
