### PR TITLE
fix(python): use resolving storage for python binding

### LINKED ISSUE #2236: Add GCS (Google Cloud Storage) support to Python bindings
## Description

The Python bindings (`pyiceberg-core`) do not support GCS-backed Iceberg tables when used with the DataFusion table provider. The underlying `iceberg-storage-opendal` crate already has full GCS support via the `opendal-gcs` feature flag, and the `OpenDalStorageFactory::Gcs` variant exists in `crates/storage/opendal/src/lib.rs` — but it is not wired up in the Python bindings.

This means anyone using pyiceberg + DataFusion with tables stored on `gs://` hits a runtime error:

```
RuntimeError: Unsupported storage scheme: gs
```

## Steps to Reproduce

```python
from pyiceberg.catalog import load_catalog
from datafusion import SessionContext

catalog = load_catalog("my_catalog")  # REST catalog pointing to GCS-backed warehouse
table = catalog.load_table("my_namespace.my_table")

ctx = SessionContext()
ctx.register_table("my_table", table)  # <-- fails here
```

Error:

```
RuntimeError: Unsupported storage scheme: gs
```

The call path is:
1. `ctx.register_table()` calls `table.__datafusion_table_provider__()`
2. pyiceberg constructs `IcebergDataFusionTable` and calls its `__datafusion_table_provider__()`
3. Rust-side `storage_factory_from_path()` in `bindings/python/src/datafusion_table_provider.rs` does not match `gs` or `gcs` schemes

### 1. Enable `opendal-gcs` feature in `bindings/python/Cargo.toml`

```diff
- iceberg-storage-opendal = { path = "../../crates/storage/opendal", features = ["opendal-s3", "opendal-fs", "opendal-memory"] }
+ iceberg-storage-opendal = { path = "../../crates/storage/opendal", features = ["opendal-s3", "opendal-fs", "opendal-memory", "opendal-gcs"] }
```

### 2. Add `gs`/`gcs` match arms in `bindings/python/src/datafusion_table_provider.rs`

In `storage_factory_from_path()`:

```diff
  let factory: Arc<dyn StorageFactory> = match scheme {
      "file" | "" => Arc::new(OpenDalStorageFactory::Fs),
      "s3" | "s3a" => Arc::new(OpenDalStorageFactory::S3 {
          configured_scheme: scheme.to_string(),
          customized_credential_load: None,
      }),
      "memory" => Arc::new(OpenDalStorageFactory::Memory),
+     "gs" | "gcs" => Arc::new(OpenDalStorageFactory::Gcs),
      _ => {
          return Err(PyRuntimeError::new_err(format!(
              "Unsupported storage scheme: {scheme}"
          )));
      }
  };
```

## Context

- The `OpenDalStorageFactory::Gcs` variant and `gcs_config_parse()` already exist in `crates/storage/opendal/src/lib.rs`
- The `opendal-gcs` feature flag is defined in `crates/storage/opendal/Cargo.toml` and is included in `opendal-all`
- GCS storage support was added to iceberg-rust in #520, with `gs://`/`gcs://` scheme support in #845 and OAuth support in #654
- This is a common use case for anyone using Google BigLake Metastore with pyiceberg and DataFusion

### PR DESCRIPTION
**Pull request by CTTY**
## Which issue does this PR close?

- Closes #2236 

## What changes are included in this PR?
- Use OpenDalResolvingStorage rather than resolving schemes directly in the python binding

### CODE REVIEW

**Comment by CTTY** [comment]
> This looks like a great addition for the python side! Looks like the cargo file only brings in s3, fs, and memory here but the resolving factory lists more storage backends from opendal.

Good point! will fix it

**Review by geruh — APPROVED** [review]
LGTM! All tests pass, built the binding and verified it works e2e with PyIceberg, and file scheme.

File: bindings/python/src/datafusion_table_provider.rs [hunk 1]
```diff
@@ -110,7 +86,7 @@ impl PyIcebergDataFusionTable {
             let table_ident = TableIdent::from_strs(identifier)
                 .map_err(|e| PyRuntimeError::new_err(format!("Invalid table identifier: {e}")))?;
 
-            let factory = storage_factory_from_path(&metadata_location)?;
+            let factory = Arc::new(OpenDalResolvingStorageFactory::new());
```
Comment (kevinjqliu) [inline bindings/python/src/datafusion_table_provider.rs:89]: love it! its like java's ResolvingFileIO

Comment (kevinjqliu) [reply bindings/python/src/datafusion_table_provider.rs:89]: maybe we can start exporting this as another FileIO for pyiceberg

File: bindings/python/Cargo.toml [hunk 2]
```diff
@@ -33,7 +33,7 @@ crate-type = ["cdylib"]
 [dependencies]
 arrow = { version = "57.1", features = ["pyarrow", "chrono-tz"] }
 iceberg = { path = "../../crates/iceberg" }
-iceberg-storage-opendal = { path = "../../crates/storage/opendal", features = ["opendal-s3", "opendal-fs", "opendal-memory"] }
+iceberg-storage-opendal = { path = "../../crates/storage/opendal", features = ["opendal-memory", "opendal-fs", "opendal-s3", "opendal-gcs", "opendal-oss", "opendal-azdls"] }
```
Comment (kevinjqliu) [inline bindings/python/Cargo.toml]: 👍 
https://github.com/apache/iceberg-rust/blob/c1497a9762b54df62343ab0239fbd07118078794/crates/storage/opendal/Cargo.toml#L31

**Review by kevinjqliu — APPROVED** [review]
LGTM!

File: bindings/python/Cargo.toml (hunk 2 above)
Comment (kevinjqliu) [reply bindings/python/Cargo.toml]: (actually can we just use `opendal-all` here?)

File: bindings/python/src/datafusion_table_provider.rs (hunk 1 above)
Comment (CTTY) [reply bindings/python/src/datafusion_table_provider.rs:89]: totally agree that we should expose something like this to Pyiceberg

There is a tracking issue to expose storage factory as a configurable item to Pyiceberg: https://github.com/apache/iceberg-rust/issues/2200
