### PR TITLE
fix(schema): check if new schema field names conflict with existing partition field names

### LINKED ISSUE #1609: Partition field and schema field name conflicts not validated on schema evolution
### Apache Iceberg Rust version

None

### Describe the bug

Same as https://github.com/apache/iceberg/issues/13833

I dont think we check for schema field and partition field name conflict when adding a new schema field
https://github.com/apache/iceberg-rust/blob/6e21b7fcfff2819e7d764b17eff066ed3424ccd5/crates/iceberg/src/spec/schema/mod.rs#L94

### To Reproduce

_No response_

### Expected behavior

_No response_

### Willingness to contribute

None

### PR DESCRIPTION
**Pull request by fvaleye**
## Which issue does this PR close?
- Closes #1609

## What changes are included in this PR?
Previously, the Iceberg Rust implementation only validated partition field names against schema field names when creating partition specs, but did not validate the reverse direction during schema evolution. This meant users could add schema fields that conflicted with existing partition field names, which could cause confusion and errors.

## Are these changes tested?
Yes, with unit tests

### CODE REVIEW

File: crates/iceberg/src/spec/table_metadata_builder.rs [hunk 1]
```diff
@@ -679,7 +682,54 @@ impl TableMetadataBuilder {
...
+    /// Check if schema field names conflict with existing partition field names.
+    ///
+    /// This validation prevents introducing new field names that match existing partition field names
+    /// that don't correspond to any field in the current schema. Field names that already exist in the
+    /// current schema are allowed since partition fields are typically derived from schema fields.
+    ///
+    /// # Errors
+    /// - Schema field name conflicts with existing partition field name that doesn't correspond to any current schema field.
+    fn check_schema_partition_name_conflicts(&self, schema: &Schema) -> Result<()> {
+        let existing_partition_field_names: HashSet<&str> = self
```
Comment (liurenjie1024) [inline crates/iceberg/src/spec/table_metadata_builder.rs]: This may be too wasteful to build a hash set for it. `Schema` already contains mapping from field name to field ids, we could go through parttion field names and lookup it in schema.

File: crates/iceberg/src/spec/table_metadata_builder.rs [hunk 2]
```diff
@@ -679,7 +682,54 @@ impl TableMetadataBuilder {
...
+            .metadata
+            .partition_specs
+            .values()
+            .flat_map(|spec| spec.fields().iter().map(|field| field.name.as_str()))
+            .collect();
+
+        let current_schema_field_names: HashSet<&str> = self
```
Comment (liurenjie1024) [inline crates/iceberg/src/spec/table_metadata_builder.rs]: This is incorrect, nested schema have more fields than first struct layer. You could use `schema.field_id_to_name_map().values` to go through all names.

File: crates/iceberg/src/spec/table_metadata_builder.rs
Comment (liurenjie1024) [inline crates/iceberg/src/spec/table_metadata_builder.rs:1]: We should also do this check when adding spec?

File: crates/iceberg/src/spec/table_metadata_builder.rs (hunk 1 above)
Comment (fvaleye) [reply crates/iceberg/src/spec/table_metadata_builder.rs]: Yes, I will adapt this approach 👍

File: crates/iceberg/src/spec/table_metadata_builder.rs
Comment (fvaleye) [reply crates/iceberg/src/spec/table_metadata_builder.rs:1]: I was asking myself the same question, but there is already a validation handled by `PartitionSpecBuilder.build()`. I added a proper testing case.

File: crates/iceberg/src/spec/table_metadata_builder.rs (hunk 2 above)
Comment (fvaleye) [reply crates/iceberg/src/spec/table_metadata_builder.rs]: I fixed it!

File: crates/iceberg/src/spec/table_metadata_builder.rs [hunk 3]
```diff
@@ -679,7 +682,41 @@ impl TableMetadataBuilder {
...
+
+        for field_name in schema.field_id_to_name_map().values() {
+            let conflicts_with_partition_field =
+                self.metadata.partition_specs.values().any(|spec| {
+                    spec.fields()
+                        .iter()
+                        .any(|partition_field| &partition_field.name == field_name)
+                });
+
+            if conflicts_with_partition_field && current_schema.field_by_name(field_name).is_none()
```
Comment (liurenjie1024) [inline crates/iceberg/src/spec/table_metadata_builder.rs]: Why we need to check current schema? Due to the multi version property of iceberg, I don't think we need to check if it's in current schema.

File: crates/iceberg/src/spec/table_metadata_builder.rs
Comment (liurenjie1024) [reply crates/iceberg/src/spec/table_metadata_builder.rs:1]: This builder only validates current schema. Due to the multi version property of iceberg, I think we should validate against all schemas?

Comment (fvaleye) [reply crates/iceberg/src/spec/table_metadata_builder.rs:1]: This is a great point.
We could introduce errors with the previous schema version 👍

Actually, for:
- Historical Schema Compatibility
- Time-Travel Queries
- Schema Evolution

I’ll add a unit test to cover this and rework it.

**Comment by fvaleye** [comment]
Thank you for your help @liurenjie1024.

Following your suggestions, I added a check for potential conflicts across different schemas.
As a side note, I also extracted two helper functions to improve focus and readability.
Would love to hear your thoughts.

**Comment by liurenjie1024** [comment]
> Following your suggestions, I added a check for potential conflicts across different schemas.
As a side note, I also extracted two helper functions to improve focus and readability.
Would love to hear your thoughts.

Hi, @fvaleye I'm fine with small refactoring as long as it's not public api.
