### PR TITLE
fix(spec): clean up -1 snapshot ID sentinel usage and add deserialization test

### LINKED ISSUE #352: Empty snapshot ID should be `Null` instead of `-1`
This is an old bug from Java. Where the Snapshot was set to -1 instead of `None`:

https://github.com/apache/iceberg-rust/blob/aba620900e99423bbd3fed969618e67e58a03a7b/crates/iceberg/src/spec/table_metadata.rs#L44

From Java 1.5 and later this is fixed. For older version of Java, the current-snapshot-id is required. We solved this by setting a flag: https://github.com/apache/iceberg-python/pull/473

### PR DESCRIPTION
**Pull request by geserdugarov**
## Which issue does this PR close?

- Closes #352.

## What changes are included in this PR?

- Replaces hardcoded `-1` with `EMPTY_SNAPSHOT_ID` constant in table metadata deserialization.
- Adds `test_empty_snapshot_id_is_normalized_to_none` to verify that the Java-style `-1` sentinel for `current-snapshot-id` is normalized to `None` during deserialization.
- Removes the public `UNASSIGNED_SNAPSHOT_ID` constant and moving it to a private constant scoped to the manifest writer module.

## Are these changes tested?

Adds a test `test_empty_snapshot_id_is_normalized_to_none` verifying the deserialization normalization.

### CODE REVIEW

File: crates/iceberg/src/spec/manifest/writer.rs [hunk 1]
```diff
@@ -32,14 +32,14 @@ use crate::spec::manifest::_serde::{ManifestEntryV1, ManifestEntryV2};
...
-    ManifestStatus, PrimitiveLiteral, SchemaRef, StructType, UNASSIGNED_SNAPSHOT_ID,
+    ManifestStatus, PrimitiveLiteral, SchemaRef, StructType,
 };
 use crate::{Error, ErrorKind};
 
 /// The builder used to create a [`ManifestWriter`].
 pub struct ManifestWriterBuilder {
     output: OutputFile,
-    snapshot_id: Option<i64>,
+    snapshot_id: i64,
```
Comment (blackmwk) [inline crates/iceberg/src/spec/manifest/writer.rs]: This is incorrect. Manifest file's snapshot id could be empty, and in this case it's inherited.

File: crates/iceberg/src/spec/manifest/writer.rs [hunk 2]
```diff
@@ -160,7 +160,7 @@ impl ManifestWriterBuilder {
 pub struct ManifestWriter {
     output: OutputFile,
 
-    snapshot_id: Option<i64>,
+    snapshot_id: i64,
```
Comment (blackmwk) [inline crates/iceberg/src/spec/manifest/writer.rs]: Ditto.

File: crates/iceberg/src/spec/manifest/writer.rs (hunk 1 above)
Comment (geserdugarov) [reply crates/iceberg/src/spec/manifest/writer.rs]: Thanks for review,  @blackmwk
My bad. I've reverted these changes. But I have to change commit message, so force pushed to 88a15464547703db6029640cf8da4db4a42fb3b2

File: crates/iceberg/src/spec/manifest/writer.rs (hunk 2 above)
Comment (geserdugarov) [reply crates/iceberg/src/spec/manifest/writer.rs]: Reverted.
