### PR TITLE
fix: incorrect Parquet INT96 timestamp values from ArrowReader

### LINKED ISSUE #2299: bug: incorrect Parquet INT96 values from ArrowReader
### Describe the bug

iceberg-rust reads INT96 timestamps incorrectly, resulting in ~1170 year offset for dates outside the nanosecond i64 range (~1677-2262).

**Example:**
- Correct (Iceberg Java): `3332-12-14 11:33:10.965`
- iceberg-rust: `2163-11-05 13:24:03.545896`

This affects migrated tables where Parquet files were written with INT96 timestamps (common for Spark/Hive migrations via `add_files` or `importSparkTable`).

#### INT96 in Parquet
INT96 is 12 bytes: 8 bytes of nanoseconds-within-day + 4 bytes of Julian day number.

#### What happens today

1. arrow-rs defaults INT96 to `Timestamp(Nanosecond, None)` ([`parquet/src/arrow/schema/primitive.rs:122`](https://github.com/apache/arrow-rs/blob/main/parquet/src/arrow/schema/primitive.rs#L122))
2. For dates outside ~1677-2262, nanoseconds-since-epoch overflows i64, producing garbage values
3. iceberg-rust's `RecordBatchTransformer` later casts to `Timestamp(Microsecond)` to match the Iceberg schema, but the data is already corrupted by overflow
4. [arrow-rs PR #7285](https://github.com/apache/arrow-rs/pull/7285) added support for reading INT96 as other TimeUnits — if you pass `Timestamp(Microsecond)` via `ArrowReaderOptions::with_schema()`, arrow-rs converts correctly without overflow

#### Why iceberg-rust doesn't pass the right schema hint

In `reader.rs`, the schema is only overridden via `ArrowReaderOptions::with_schema()` when Parquet files lack field IDs (branches 2/3 of the schema resolution strategy). Even then, the overridden schema is derived from the Parquet file metadata — which has
`Timestamp(Nanosecond)` for INT96 columns — not from the Iceberg table schema which correctly specifies `Timestamp(Microsecond)`.

For files with embedded field IDs (branch 1), no schema override is passed at all.

### How Iceberg Java handles this

Iceberg Java avoids this entirely by using a **custom INT96 column reader** that bypasses parquet-mr's default decoding. The reader factory receives the Iceberg expected schema as the authority via `readerFuncWithSchema.apply(expectedSchema, fileType)` ([`Parquet.java:1366-1371`](https://github.com/apache/iceberg/blob/main/parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java#L1366-L1371)).

When `BaseParquetReaders.primitive()` encounters INT96, it dispatches to a `TimestampInt96Reader` that reads the raw 12 bytes and converts safely:

```java
// GenericParquetReaders.java:172-191
final ByteBuffer byteBuffer = column.nextBinary().toByteBuffer().order(ByteOrder.LITTLE_ENDIAN);
final long timeOfDayNanos = byteBuffer.getLong();
final int julianDay = byteBuffer.getInt();

return Instant.ofEpochMilli(TimeUnit.DAYS.toMillis(julianDay - UNIX_EPOCH_JULIAN))
    .plusNanos(timeOfDayNanos)
    .atOffset(ZoneOffset.UTC);
```

This avoids overflow by keeping days and nanos separate — it never tries to cram the full value into a single i64 nanoseconds-since-epoch.

iceberg-rust can't easily replicate this custom column reader approach since it delegates to arrow-rs for Parquet reading. The equivalent fix is to pass the correct schema hint so arrow-rs decodes INT96 as microseconds.

### Proposed Fix

When building the Arrow schema to pass to `ArrowReaderOptions::with_schema()`, overlay the Iceberg table schema's timestamp types onto the Parquet-derived schema. For any column where:
- The Parquet physical type is INT96
- The Iceberg type is Timestamp or Timestamptz

Replace `Timestamp(Nanosecond, ...)` with `Timestamp(Microsecond, ...)` in the schema hint. This triggers arrow-rs's INT96 conversion logic from [PR #7285](https://github.com/apache/arrow-rs/pull/7285).

This is the same approach DataFusion uses via its `coerce_int96_to_resolution()` function ([datafusion PR #15537](https://github.com/apache/datafusion/pull/15537)), except the source of truth for the target TimeUnit is the Iceberg schema rather than a user config.

#### Files to modify

1. `crates/iceberg/src/arrow/reader.rs`
   - After building the Arrow schema from Parquet metadata, walk INT96 timestamp columns and replace their types with the Iceberg schema's timestamp type
   - This applies to all three branches of the schema resolution strategy (with/without field IDs, with/without name mapping)

### Related

- [arrow-rs #7285](https://github.com/apache/arrow-rs/pull/7285): Support different TimeUnits and timezones when reading Timestamps from INT96
- [datafusion #15537](https://github.com/apache/datafusion/pull/15537): INT96 handling in DataFusion
- [datafusion-comet #3856](https://github.com/apache/datafusion-comet/issues/3856): Downstream issue in Comet

### PR DESCRIPTION
**Pull request by mbutrovich**
## Which issue does this PR close?

- Closes #2299.
## What changes are included in this PR?
- Add `coerce_int96_timestamps()` to patch the Arrow schema before reading, using arrow-rs's schema hint mechanism (`ArrowReaderOptions::with_schema`) to read
INT96 columns at the resolution specified by the Iceberg table schema
- `timestamp`/`timestamptz` → microsecond, `timestamp_ns`/`timestamptz_ns` → nanosecond, per the [Iceberg spec](https://iceberg.apache.org/spec/#primitive-types)
- Falls back to microsecond when no field ID is available (matching Iceberg Java's `TimestampInt96Reader` behavior)
- Applied after all three schema resolution branches (with field IDs, name mapping, positional fallback) so the fix covers both native and migrated tables
- Handles INT96 inside nested types (structs, lists, maps) via `ArrowSchemaVisitor` traversal
- Visitor and tests live in a standalone `arrow/int96.rs` module to keep `reader.rs` manageable
- Made `visit_schema` in `arrow/schema.rs` `pub(crate)` so the coercion visitor can reuse the existing traversal

## Are these changes tested?

- `test_read_int96_timestamps_with_field_ids` — files with embedded field IDs (branch 1)
- `test_read_int96_timestamps_without_field_ids` — migrated files without field IDs (branches 2/3)
- `test_read_int96_timestamps_in_struct` — INT96 inside a struct field
- `test_read_int96_timestamps_in_list` — INT96 inside a list field (3-level Parquet LIST encoding)
- `test_read_int96_timestamps_in_map` — INT96 as map values
- All tests use dates outside the i64 nanosecond range (~1677-2262) to confirm the overflow is avoided
- [Apache DataFusion Comet](https://github.com/apache/datafusion-comet) used the repro test in
[apache/datafusion-comet#3856](https://github.com/apache/datafusion-comet/issues/3856) and it passes with this change:
https://github.com/apache/datafusion-comet/pull/3857

### CODE REVIEW

File: crates/iceberg/src/arrow/reader.rs [hunk 1]
```diff
@@ -386,6 +386,27 @@ impl ArrowReader {
...
+            arrow_metadata.metadata().file_metadata().schema_descr(),
+            arrow_metadata.schema(),
+            &task.schema,
+        ) {
+            let options = ArrowReaderOptions::new().with_schema(coerced_schema);
+            ArrowReaderMetadata::try_new(Arc::clone(arrow_metadata.metadata()), options).map_err(
+                |e| {
+                    Error::new(
+                        ErrorKind::Unexpected,
+                        "Failed to create ArrowReaderMetadata with INT96-coerced schema",
```
Comment (emkornfield) [inline crates/iceberg/src/arrow/reader.rs]: should we include the coerced schema or something else to help debug?

File: crates/iceberg/src/arrow/reader.rs [hunk 2]
```diff
@@ -1232,6 +1253,121 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+///
+/// References:
+/// - Iceberg spec primitive types: <https://iceberg.apache.org/spec/#primitive-types>
+/// - arrow-rs schema hint support: <https://github.com/apache/arrow-rs/pull/7285>
+fn coerce_int96_timestamps(
+    parquet_schema: &SchemaDescriptor,
+    arrow_schema: &ArrowSchemaRef,
+    iceberg_schema: &Schema,
+) -> Option<Arc<ArrowSchema>> {
+    use arrow_schema::{DataType, Field, Fields, TimeUnit};
```
Comment (emkornfield) [inline crates/iceberg/src/arrow/reader.rs]: I've received prior feedback, that I think the general preference to do imports at the top of the modules.  I would guess this applies here but maybe there is an exception for arrow.

File: crates/iceberg/src/arrow/reader.rs [hunk 3]
```diff
@@ -1232,6 +1253,121 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+        .iter()
+        .filter(|col| col.physical_type() == PhysicalType::INT96)
+        .map(|col| col.path().string())
+        .collect();
+
+    if int96_paths.is_empty() {
+        return None;
+    }
+
+    fn coerce_field(
```
Comment (emkornfield) [inline crates/iceberg/src/arrow/reader.rs]: nit: this seems like a pretty big function to embed within this function?

File: crates/iceberg/src/arrow/reader.rs [hunk 4]
```diff
@@ -1232,6 +1253,121 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+    iceberg_schema: &Schema,
+) -> Option<Arc<ArrowSchema>> {
+    use arrow_schema::{DataType, Field, Fields, TimeUnit};
+    use parquet::basic::Type as PhysicalType;
+
+    let int96_paths: HashSet<String> = parquet_schema
+        .columns()
+        .iter()
+        .filter(|col| col.physical_type() == PhysicalType::INT96)
+        .map(|col| col.path().string())
```
Comment (emkornfield) [inline crates/iceberg/src/arrow/reader.rs]: Is it possible to store/compare the ColumnPath directly instead of converting to/from string.

File: crates/iceberg/src/arrow/reader.rs [hunk 5]
```diff
@@ -1232,6 +1253,121 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+                )
+            }
+            _ => Arc::clone(field),
+        }
+    }
+
+    let coerced_fields: Vec<FieldRef> = arrow_schema
+        .fields()
+        .iter()
+        .map(|field| {
```
Comment (emkornfield) [inline crates/iceberg/src/arrow/reader.rs]: it seems like it would be nice to stop early once all fields are replaced (and possibly have a more targeted search).

File: crates/iceberg/src/arrow/reader.rs [hunk 6]
```diff
@@ -1232,6 +1253,121 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+    }
+
+    fn coerce_field(
+        field: &FieldRef,
+        path_parts: &[&str],
+        int96_paths: &HashSet<String>,
+        iceberg_schema: &Schema,
+    ) -> FieldRef {
+        match field.data_type() {
+            DataType::Struct(fields) => {
```
Comment (emkornfield) [inline crates/iceberg/src/arrow/reader.rs]: what about maps and lists?

**Comment by mbutrovich** [comment]
Thanks for the feedback @emkornfield! You gave me a good idea on how I might be able to restructure this to address several of your comments. If you don't mind, I'll re-request a review probably later today.

File: crates/iceberg/src/arrow/reader.rs (hunk 2 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: Will do, thanks!

File: crates/iceberg/src/arrow/reader.rs (hunk 3 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: I'll find a cleaner way to break this us.

File: crates/iceberg/src/arrow/reader.rs (hunk 1 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: Will do, thanks!

File: crates/iceberg/src/arrow/reader.rs (hunk 4 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: Yep, just stuck closer to what landed in DataFusion: https://github.com/apache/datafusion/blob/e74b83ab026379158a8031c9d70f187fbb704172/datafusion/datasource-parquet/src/file_format.rs#L725

File: crates/iceberg/src/arrow/reader.rs (hunk 5 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: Will do, thanks!

File: crates/iceberg/src/arrow/reader.rs (hunk 6 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: Good catch, let me handle those and add respective tests.

**Comment by emkornfield** [comment]
> Thanks for the feedback @emkornfield! You gave me a good idea on how I might be able to restructure this to address several of your comments. If you don't mind, I'll re-request a review probably later today.

Sounds good, please take comments with a grain of salt, I'm fairly new the code base.

File: crates/iceberg/src/arrow/reader.rs [hunk 7]
```diff
@@ -1232,6 +1257,202 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+            // Parquet 3-level LIST encoding inserts a repeated group between the list
+            // and its element, e.g. `my_list.list.element` where `list` is the
+            // intermediate group. The group name varies across writers — the spec says
+            // "list" but legacy data uses "element", "array", `<parent>_tuple`, etc.
+            // We skip it (depth + 1) since we navigate by Parquet ColumnPath parts
+            // which contain the actual name from the file. See the Parquet LogicalTypes
+            // spec for the backward-compatibility rules:
+            // https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#lists
+            if depth + 2 < parquet_path.len() {
+                debug_assert_eq!(
```
Comment (emkornfield) [inline crates/iceberg/src/arrow/reader.rs]: This is a can of worms I think, I don't have any great suggestions for making this robust, but I can guarantee there are likely issues for some set of parquet files.

File: crates/iceberg/src/arrow/reader.rs [hunk 8]
```diff
@@ -1232,6 +1257,202 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+                        DataType::LargeList(_) => DataType::LargeList(new_element),
+                        _ => unreachable!(),
+                    };
+                    let new_field = Arc::new(
+                        Field::new(field.name(), new_type, field.is_nullable())
+                            .with_metadata(field.metadata().clone()),
+                    );
+                    return (new_field, true);
+                }
+            }
```
Comment (emkornfield) [inline crates/iceberg/src/arrow/reader.rs]: we should consider logging on the else branch to indicate it was not of expected type and therefore not fixed up.

File: crates/iceberg/src/arrow/reader.rs [hunk 9]
```diff
@@ -1232,6 +1257,202 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+                        Field::new(
+                            field.name(),
+                            DataType::Map(new_entries, *sorted),
+                            field.is_nullable(),
+                        )
+                        .with_metadata(field.metadata().clone()),
+                    );
+                    return (new_field, true);
+                }
+            }
```
Comment (emkornfield) [inline crates/iceberg/src/arrow/reader.rs]: same comment on logging as above.

File: crates/iceberg/src/arrow/reader.rs (hunk 7 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: Should I just relax it and take out the `debug_assert`?

Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: Removed.

File: crates/iceberg/src/arrow/reader.rs (hunk 8 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: I don't see a good form of logging in the codebase yet, but that's a good point. I'll bring it up at the next sync.

File: crates/iceberg/src/arrow/reader.rs (hunk 9 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: Same as above.

File: crates/iceberg/src/arrow/reader.rs [hunk 10]
```diff
@@ -1232,6 +1257,195 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+/// ~1677-2262. We use arrow-rs's schema hint mechanism to read INT96 at the resolution
+/// specified by the Iceberg schema (`timestamp` → microsecond, `timestamp_ns` → nanosecond).
+///
+/// Iceberg Java handles this differently: it bypasses parquet-mr with a custom column reader
+/// (`GenericParquetReaders.TimestampInt96Reader`). We achieve the same result via schema hints.
+///
+/// References:
+/// - Iceberg spec primitive types: <https://iceberg.apache.org/spec/#primitive-types>
+/// - arrow-rs schema hint support: <https://github.com/apache/arrow-rs/pull/7285>
+fn coerce_int96_timestamps(
```
Comment (blackmwk) [inline crates/iceberg/src/arrow/reader.rs]: This is quite hacky. How about we rewrite it with ArrowSchemaVisitorWithPartner?

Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: I'll take a look, thanks for the feedback @blackmwk!

**Comment by mbutrovich** [comment]
Rewrote using `ArrowSchemaVisitor`, following the same pattern as `MetadataStripVisitor`. The visitor walks the Arrow schema and at each primitive, checks if it's `Timestamp(Nanosecond)` and looks up the Iceberg field by ID to determine the target resolution.

This also eliminates the `parquet_schema` parameter entirely — we no longer need Parquet column paths to find INT96 columns, since arrow-rs only produces `Timestamp(Nanosecond)` for INT96 (INT64 timestamps get the correct unit from Parquet metadata).                                       

Made `visit_schema` `pub(crate)` so it's accessible from `reader.rs`.

File: crates/iceberg/src/arrow/reader.rs [hunk 11]
```diff
@@ -1232,6 +1255,203 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+    if visitor.changed {
+        Some(Arc::new(coerced))
+    } else {
+        None
+    }
+}
+
+/// Visitor that coerces `Timestamp(Nanosecond)` Arrow fields to the resolution
+/// indicated by the Iceberg schema. Follows the same pattern as `MetadataStripVisitor`.
+struct Int96CoercionVisitor<'a> {
```
Comment (blackmwk) [inline crates/iceberg/src/arrow/reader.rs]: Please move this struct and its ut to a standalone module. This file is already too large.

File: crates/iceberg/src/arrow/reader.rs [hunk 12]
```diff
@@ -1232,6 +1255,203 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+        self.field_stack.push(field.as_ref().clone());
+        Ok(())
+    }
+
+    fn before_map_value(&mut self, field: &Field) -> Result<()> {
+        self.field_stack.push(field.as_ref().clone());
+        Ok(())
+    }
+
+    fn schema(&mut self, schema: &ArrowSchema, values: Vec<Self::T>) -> Result<Self::U> {
```
Comment (blackmwk) [inline crates/iceberg/src/arrow/reader.rs]:
```suggestion
    fn schema(&mut self, schema: &ArrowSchema, values: Vec<Field>) -> Result<ArrowSchema> {
```

Please don't use self type here, it's difficult to read.

Comment (blackmwk) [reply crates/iceberg/src/arrow/reader.rs]: Please change all methods.

File: crates/iceberg/src/arrow/reader.rs [hunk 13]
```diff
@@ -1232,6 +1255,203 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+    } else {
+        None
+    }
+}
+
+/// Visitor that coerces `Timestamp(Nanosecond)` Arrow fields to the resolution
+/// indicated by the Iceberg schema. Follows the same pattern as `MetadataStripVisitor`.
+struct Int96CoercionVisitor<'a> {
+    iceberg_schema: &'a Schema,
+    field_stack: Vec<Field>,
```
Comment (blackmwk) [inline crates/iceberg/src/arrow/reader.rs]: This is too heavy, we should store `FieldRef`. We may need to change ArrowSchemaVisitor's method signature, please create an issue to track it.

File: crates/iceberg/src/arrow/reader.rs [hunk 14]
```diff
@@ -1232,6 +1255,203 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+        Ok(ArrowSchema::new_with_metadata(
+            values,
+            schema.metadata().clone(),
+        ))
+    }
+
+    fn r#struct(&mut self, _fields: &Fields, results: Vec<Self::T>) -> Result<Self::T> {
+        let field_info = self
+            .field_stack
+            .pop()
```
Comment (blackmwk) [inline crates/iceberg/src/arrow/reader.rs]: We could do pop in after_field method.

File: crates/iceberg/src/arrow/reader.rs [hunk 15]
```diff
@@ -1232,6 +1255,203 @@ fn add_fallback_field_ids_to_arrow_schema(arrow_schema: &ArrowSchemaRef) -> Arc<
...
+        if target == TimeUnit::Nanosecond {
+            None
+        } else {
+            Some(target)
+        }
+    }
+}
+
+impl ArrowSchemaVisitor for Int96CoercionVisitor<'_> {
+    type T = Field;
```
Comment (blackmwk) [inline crates/iceberg/src/arrow/reader.rs]: Should this be `FieldRef`?

File: crates/iceberg/src/arrow/reader.rs (hunk 11 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: Agreed. I've been spending a lot of time in `reader.rs` and it's gotten pretty unwieldy.

File: crates/iceberg/src/arrow/reader.rs (hunk 13 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: Opened an issue and will leave a comment in the code about it.

https://github.com/apache/iceberg-rust/issues/2310

**Comment by mbutrovich** [comment]
Most recent changes:

1. **Standalone module** — Moved `coerce_int96_timestamps`, `Int96CoercionVisitor`, and all 5 INT96 tests to `crates/iceberg/src/arrow/int96.rs`. Registered in `mod.rs`.
2. **Concrete types** — Replaced `Self::T`/`Self::U` with `Field`/`ArrowSchema` in all `ArrowSchemaVisitor` method signatures.
3. **Pop in `after_*` methods** — Push in `before_field`/`before_list_element`/`before_map_key`/`before_map_value`, pop in the corresponding `after_*` methods. `primitive`/`struct`/`list`/`map` now peek with `.last()` instead of `.pop()`.
4. **`FieldRef` in field_stack** — Kept `Vec<Field>` for now since the trait passes `&Field`. Added `// TODO(#2310)` comment referencing the tracking issue.


Thanks for the patience so far @blackmwk!

File: crates/iceberg/src/arrow/reader.rs (hunk 15 above)
Comment (mbutrovich) [reply crates/iceberg/src/arrow/reader.rs]: I think we have to wait for #2310 for this one. The trait currently passes `&Field` in `before_field`/`after_field`, so getting a `FieldRef` requires cloning into a new `Arc`. Once #2310 changes the trait to pass `&FieldRef`, we can store `Vec<FieldRef>` and the push becomes a cheap `Arc::clone`.

File: crates/iceberg/src/arrow/int96.rs [hunk 16]
```diff
@@ -0,0 +1,804 @@
...
+                *expected,
+                "Row {i}: got {}, expected {expected}",
+                ts_array.value(i)
+            );
+        }
+    }
+
+    /// Files with embedded field IDs (branch 1 of schema resolution).
+    #[tokio::test]
+    async fn test_read_int96_timestamps_with_field_ids() {
```
Comment (blackmwk) [inline crates/iceberg/src/arrow/int96.rs]: As ut, I expect to see tests for the schema visitor only. I think it would be better to put these tests into reader module?

Comment (mbutrovich) [reply crates/iceberg/src/arrow/int96.rs]: Thanks for the review @blackmwk!

**Moved integration tests from `int96.rs` to `reader.rs`**
- The 5 tests that write Parquet files and read through `ArrowReader` now live in the `reader` test module where they belong.
- Converted `///` doc comments to `//` to match codebase test style.

**Added 11 unit tests for the schema visitor in `int96.rs`**
- `test_coerce_timestamp_ns_to_us` — `Timestamp` field ID → microsecond
- `test_coerce_timestamptz_ns_to_us` — `Timestamptz` field ID → microsecond, preserves timezone
- `test_no_coercion_when_iceberg_is_timestamp_ns` — `TimestampNs` → no change
- `test_no_coercion_when_iceberg_is_timestamptz_ns` — `TimestamptzNs` → no change
- `test_no_coercion_when_already_microsecond` — already microsecond → no change
- `test_defaults_to_us_without_field_ids` — no field ID metadata → falls back to microsecond (Iceberg Java behavior)
- `test_defaults_to_us_when_iceberg_type_is_not_timestamp` — field ID maps to non-timestamp Iceberg type → falls back to microsecond
- `test_coerce_preserves_field_metadata` — field metadata survives coercion
- `test_coerce_timestamp_in_struct` — nested struct coercion
- `test_coerce_timestamp_in_list` — nested list coercion
- `test_coerce_timestamp_in_map_value` — nested map value coercion

**Review by blackmwk — APPROVED** [review]
Thanks @mbutrovich for this pr!
