### PR TITLE
fix: enable public access to ManifestEntry properties

### LINKED ISSUE #282: fix: Making ManifestEntry API public
According to the original design, `FileScanTask` can be transformed to arrow record batch stream for query purposes, however, there are cases in which consumers or API users will be interested in accessing file metadata for different purposes such as using the table with other query engines (that require a list of file paths), or for monitoring purpose to track the table health.

### PR DESCRIPTION
**Pull request by a-agmon**
resolves #282 
The purpose of the PR is to change the ManifestEntry properties and FileScanTask data_file() method to public in order to enable public access to the file metadata API.
Some consumers are interested in the file paths that are part of the current table and their properties for query and monitoring purposes.

### CODE REVIEW

**Comment by a-agmon** [comment]
Just to add a motivation the purpose is to allow this kind of API access:

```rust
    let mut stream = table_scan.plan_files().await?;
    while let Some(file) = stream.next().await {
        let data_file = file?.data_file();
        println!("---------------------------------");
        println!("File Path: {:?}", data_file.file_path());
        println!("File Size: {:?}", data_file.file_size_in_bytes());
    }

```
My team is using these APIs to creat a layer of monitoring on top of Iceberg table that can help track issues and identify problems

File: crates/iceberg/src/spec/manifest.rs [hunk 1]
```diff
@@ -1049,7 +1049,7 @@ pub struct DataFile {
     /// order id to null. Readers must ignore sort order id for position
     /// delete files.
     #[builder(default, setter(strip_option))]
-    pub(crate) sort_order_id: Option<i32>,
+    pub sort_order_id: Option<i32>,
```
Comment (Xuanwo) [inline crates/iceberg/src/spec/manifest.rs:1052]: I remembered that we don't want users to access those fields directly. 

cc @liurenjie1024 for ideas.

File: crates/iceberg/src/scan.rs [hunk 2]
```diff
@@ -209,7 +209,7 @@ pub struct FileScanTask {
 pub type ArrowRecordBatchStream = BoxStream<'static, crate::Result<RecordBatch>>;
 
 impl FileScanTask {
-    pub(crate) fn data_file(&self) -> ManifestEntryRef {
+    pub fn data_file(&self) -> ManifestEntryRef {
```
Comment (Xuanwo) [inline crates/iceberg/src/scan.rs:212]: This change looks good to me.

File: crates/iceberg/src/spec/manifest.rs (hunk 1 above)
Comment (liurenjie1024) [reply crates/iceberg/src/spec/manifest.rs:1052]: Yes, I prefer to add getter methods for these fields rather accessing fields directly.

**Review by liurenjie1024 — COMMENTED** [review]
Hi @a-agmon Thanks for this pr. But per our previous discussion, we prefer to expose getter methods rather fields directly to user, you can see [the discussion](https://github.com/apache/iceberg-rust/issues/3) here.

**Comment by a-agmon** [comment]
Hi @liurenjie1024 , @Xuanwo 
I have addressed the issues and updated the PR.
Please let me know what do you think

File: crates/iceberg/src/spec/manifest.rs [hunk 3]
```diff
@@ -1052,6 +1052,89 @@ pub struct DataFile {
     pub(crate) sort_order_id: Option<i32>,
 }
 
+impl DataFile {
+    /// Get the content type of the data file (data, equality deletes, or position deletes)
+    pub fn content(&self) -> DataContentType {
```
Comment (liurenjie1024) [inline crates/iceberg/src/spec/manifest.rs:1057]: We can have `#[inline]` attribute to give compiler a hint, but this is optional.

**Review by liurenjie1024 — APPROVED** [review]
LGTM, thanks @a-agmon !

File: crates/iceberg/src/spec/manifest.rs (hunk 3 above)
Comment (a-agmon) [reply crates/iceberg/src/spec/manifest.rs:1057]: Thanks @liurenjie1024 , You mean to `#[inline]` all pub methods on DataFile? 
I actually thought about this, but then saw that inline was not used on other pub struct methods (such as Table, Namespace, etc) so preferred to maintain consistency. 
If you think its better then I will do this

Comment (liurenjie1024) [reply crates/iceberg/src/spec/manifest.rs:1057]: I think it's fine for now, and we could add it later when necessary, thanks!

**Comment by liurenjie1024** [comment]
cc @Xuanwo Any other comments?
