### PR TITLE
fix: Reserved sort order ID cannot contain any fields

### LINKED ISSUE #1963: Missing validation for reserved sort order ID 0 during metadata JSON parsing
### Apache Iceberg Rust version

None

### Describe the bug

The spec reserved `order-id: 0` for the unsorted order, but iceberg-rust parser incorrectly accepts `order-id: 0` with arbitrary fields set.

Unlike other metadata validations (schema, partition spec, snapshots), this constraint is not enforced during JSON parsing, though `SortOrderBuilder::build_unbound()` does validate it.

This seems like a simple oversight. adding similar validation in `TableMetadata::try_normalize_sort_order()` should fix it.

### To Reproduce

```rust
#[test]
fn test_invalid_sort_order_id_zero_with_fields() {
    let metadata = r#"
    {
        "format-version": 2,
        "table-uuid": "9c12d441-03fe-4693-9a96-a0705ddf69c1",
        "location": "s3://bucket/test/location",
        "last-sequence-number": 111,
        "last-updated-ms": 1600000000000,
        "last-column-id": 3,
        "current-schema-id": 1,
        "schemas": [
            {
                "type": "struct",
                "schema-id": 1,
                "fields": [
                    {"id": 1, "name": "x", "required": true, "type": "long"},
                    {"id": 2, "name": "y", "required": true, "type": "long"}
                ]
            }
        ],
        "default-spec-id": 0,
        "partition-specs": [{"spec-id": 0, "fields": []}],
        "last-partition-id": 999,
        "default-sort-order-id": 0,
        "sort-orders": [
            {
                "order-id": 0,
                "fields": [
                    {
                        "transform": "identity",
                        "source-id": 1,
                        "direction": "asc",
                        "null-order": "nulls-first"
                    }
                ]
            }
        ],
        "properties": {},
        "current-snapshot-id": -1,
        "snapshots": []
    }
    "#;

    let result: Result<TableMetadata, serde_json::Error> = serde_json::from_str(metadata);

    // BUG: This should fail but currently succeeds.
    assert!(
        result.is_ok(),
        "BUG: Parsing should fail for sort order ID 0 with fields, but currently succeeds"
    );

    let table_metadata = result.unwrap();
    let sort_order = table_metadata.sort_order_by_id(0).unwrap();
    assert!(
        !sort_order.fields.is_empty(),
        "BUG: Sort order 0 should not have fields per spec"
    );
}
```

### Expected behavior

Invalid metadata should be reject

### Willingness to contribute

None

### PR DESCRIPTION
**Pull request by aditya-subrahmanyan**
## Which issue does this PR close?

- Closes #1963.

## What changes are included in this PR?

This change validates that table metadata with reserved sort order ID (0) cannot contain fields associated with it. If this is found, we error out instead of silently parsing arbitrary field values.

## Are these changes tested?

Added the unit test described in the issue and verified that the check is now enforced.

### CODE REVIEW

**Comment by aditya-subrahmanyan** [comment]
@CTTY: Please review this PR when you get a chance, thanks.

File: crates/iceberg/src/spec/table_metadata.rs [hunk 1]
```diff
@@ -506,6 +506,19 @@ impl TableMetadata {
 
     /// If the default sort order is unsorted but the sort order is not present, add it
     fn try_normalize_sort_order(&mut self) -> Result<()> {
+        // Validate that sort order ID 0 (reserved for unsorted) has no fields
+        if let Some(sort_order) = self.sort_order_by_id(SortOrder::UNSORTED_ORDER_ID)
+            && !sort_order.fields.is_empty()
+        {
+            return Err(Error::new(
```
Comment (Fokko) [inline crates/iceberg/src/spec/table_metadata.rs:513]: Do we want to fail, or do we want to drop the fields and emit a warning?

Comment (aditya-subrahmanyan) [reply crates/iceberg/src/spec/table_metadata.rs:513]: It looks like we don't allow non-empty `fields` for reserved sort order ID: https://github.com/apache/iceberg/blob/main/api/src/main/java/org/apache/iceberg/SortOrder.java#L269

IMO it feels safer to just report an error to the client that there's something "fishy" about their metadata. What do you think?

File: crates/iceberg/src/spec/table_metadata.rs [hunk 2]
```diff
@@ -506,6 +506,19 @@ impl TableMetadata {
...
+                ErrorKind::DataInvalid,
```
Comment (CTTY) [inline crates/iceberg/src/spec/table_metadata.rs]: nit: This should be `ErrorKind::Unexpected` according to https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/spec/sort.rs#L157

File: crates/iceberg/src/spec/table_metadata.rs (hunk 1 above)
Comment (CTTY) [reply crates/iceberg/src/spec/table_metadata.rs:513]: +1 I think failing here is better and more consistent to Java's behavior

**Review by CTTY — APPROVED** [review]
LGTM! 

I'm not very familiar with the code path and was wondering why we need to use [try_normalize](https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/spec/table_metadata.rs#L477)  to do the validation when parsing `TableMetadata`. Looking at iceberg-java's [TableMetadataParser](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/TableMetadataParser.java#L453), it just delegates the validation to sub-parsers like `PartitionSpecParser` and `SortOrderBuilder`, which I think is a much cleaner pattern so we don't have to rewrite the validation logic.  In rust, we probably need to implement deserializer for `SortOrder`, `PartitionSpec` and so on individually to adopt this pattern.

This concern should not block this PR tho

File: crates/iceberg/src/spec/table_metadata.rs (hunk 2 above)
Comment (aditya-subrahmanyan) [reply crates/iceberg/src/spec/table_metadata.rs]: Ack, updated in a new commit as part of the PR

**Comment by aditya-subrahmanyan** [comment]
Hi @Fokko , please review when you get a chance. Thanks!

File: crates/iceberg/src/spec/table_metadata.rs (hunk 1 above)
Comment (liurenjie1024) [reply crates/iceberg/src/spec/table_metadata.rs:513]: +1, I also think it's more reasonable to fail it.

**Review by liurenjie1024 — APPROVED** [review]
Thanks @aditya-subrahmanyan for this fix!
