### PR TITLE
fix: fix parse partitions in manifest_list

### LINKED ISSUE #119: Support `initial-default` when reading Avro
I would suggest adding support for `initial-default` to read V1 Avro files into V2 objects in memory.

For example, V1 does not have sequence numbers, and then need to be set to `0`. This is important when you have a V1 table, and then you upgrade it to V2, the underlying Avro files are still V1 until you rewrite everything. See comment here: https://github.com/apache/iceberg-rust/pull/79#discussion_r1425117160

With the initial-default you could just read a `0` if the field is not present.

### LINKED ISSUE #121: bug: ManifestList parsing should not require `partition_type`.
In [manifest list parser](https://github.com/apache/iceberg-rust/blob/82e129945bed150b6d9fbcb93ebb4d92f8150895/crates/iceberg/src/spec/manifest_list.rs#L57), we ask user to pass in a `partition_type`. This is incorrect since different manifest file may have different partition spec, so we should ask user to pass a `HashMap<i32, StructType>`, e.g. a mapping from partition spec id to partition type. See https://iceberg.apache.org/spec/#snapshots

### PR DESCRIPTION
**Pull request by ZENOTME**
This PR:
1. fix #121 and modify unit test to test this case.
2. fix #119, add init default when reading v1 manifest
3. add test case for writing back v1 manifest/manifest-list as v2 
   - for manifest list, we can directly write back a manifest list as v2.
   - for manifest, we can call `upgrade_version` and then write it back as v2.

### CODE REVIEW

**Comment by ZENOTME** [comment]
cc @Fokko @liurenjie1024  @Xuanwo @JanKaul

File: crates/iceberg/src/spec/manifest.rs [hunk 1]
```diff
@@ -79,6 +79,22 @@ impl Manifest {
 
         Ok(Manifest { metadata, entries })
     }
+
+    /// Upgrade the format version of this manifest.
+    pub fn upgrade_version(&mut self, format_version: FormatVersion) -> Result<(), Error> {
```
Comment (Xuanwo) [inline crates/iceberg/src/spec/manifest.rs:84]: update version seems tricky to me. We don't need to take other actions?

File: crates/iceberg/src/spec/manifest_list.rs [hunk 2]
```diff
@@ -820,15 +834,24 @@ pub(super) mod _serde {
                     .zip(partition_types)
                     .map(|(v, field)| v.try_into(&field.field_type))
                     .collect::<Result<Vec<_>, _>>()
-            })
-            .transpose()?
-            .unwrap_or_default())
+            } else {
+                Err(Error::new(
+                    crate::ErrorKind::DataInvalid,
```
Comment (liurenjie1024) [inline crates/iceberg/src/spec/manifest_list.rs:839]: I'm expecting a better error message with more context, for example, the manifest list file path, the entry path, spec id.

File: crates/iceberg/src/spec/manifest.rs (hunk 1 above)
Comment (liurenjie1024) [reply crates/iceberg/src/spec/manifest.rs:84]: +1 for this concern. Version upgrade is part of transaction api, it involves full rewrite of all things like snapshot, and should not do it here.

Comment (ZENOTME) [reply crates/iceberg/src/spec/manifest.rs:84]: > +1 for this concern. Version upgrade is part of transaction api, it involves full rewrite of all things like snapshot, and should not do it here.

Yes, upgrading the version is more. Here it's more like upgrading this manifest file. https://github.com/apache/iceberg-rust/issues/119#issuecomment-1855355460
This interface is confusing.  There is another way:
1. `pub fn parse_avro(bs: &[u8], version) -> Result<Self, Error>`. Then we can parse v1 manifest as v2. After we parse it, we will modify the version as v2. 
2. `pub async fn write(mut self, manifest: Manifest, version)`. And then we can write as v1 manifest as v2. I think this way may be more clear.🤔

Comment (liurenjie1024) [reply crates/iceberg/src/spec/manifest.rs:84]: I checked that comment, but I don't think we need to introduce this api for now. The manifest format upgradation is part of table format upgradation, and we need to think about it in the overall design, rather exposing this single api.

Comment (ZENOTME) [reply crates/iceberg/src/spec/manifest.rs:84]: LGTM. Let's remove this interface and only fix the init-default. Let's track the upgrade action in another issue as a new feature.

File: crates/iceberg/src/spec/manifest_list.rs (hunk 2 above)
Comment (ZENOTME) [reply crates/iceberg/src/spec/manifest_list.rs:855]: Have added context of entry path and spec id. We don't have the manifest list file path for now (we pass [u8] to parse directly), I think it need to set in the high level API.

**Review by liurenjie1024 — APPROVED** [review]
LGTM, thanks!

**Review by Xuanwo — APPROVED** [review]
Thanks!

File: crates/iceberg/src/spec/manifest.rs [hunk 3]
```diff
@@ -1104,8 +1104,8 @@ mod _serde {
             Ok(ManifestEntry {
                 status: self.status.try_into()?,
                 snapshot_id: Some(self.snapshot_id),
-                sequence_number: None,
-                file_sequence_number: None,
+                sequence_number: Some(0),
```
Comment (Fokko) [inline crates/iceberg/src/spec/manifest.rs:1107]: This is correct 👍

File: crates/iceberg/src/spec/manifest.rs (hunk 1 above)
Comment (Fokko) [reply crates/iceberg/src/spec/manifest.rs]: > +1 for this concern. Version upgrade is part of transaction api, it involves full rewrite of all things like snapshot, and should not do it here.

This is not correct, and V2 is forward-compatible. If you apply the rules of schema evolution (as with any other Iceberg table), it should work seamlessly. You don't want to rewrite a multi-petabyte table when you do any meta operation.

Comment (Fokko) [reply crates/iceberg/src/spec/manifest.rs]: > Let's remove this interface and only fix the init-default.

This will make thing easier, such as setting the sequence-number when the field isn't present (in the case of V1 metadata).
