### PR TITLE
fix: Fix namespace identifier in url

### LINKED ISSUE #433: bug: invalid unicode transfer in Catalog namespace interface
replace test unit `rest_catalog_test::test_list_empty_namespace` to this:
```
#[tokio::test]
async fn test_list_empty_namespace() {
    let fixture = get_test_fixture("test_list_empty_namespace").await;

    let ns_apple = Namespace::with_properties(
        NamespaceIdent::from_strs(["a_a", "apple"]).unwrap(),
        HashMap::from([
            ("owner".to_string(), "ray".to_string()),
            ("community".to_string(), "apache".to_string()),
        ]),
    );

    // Currently this namespace doesn't exist, so it should return error.
    assert!(fixture
        .rest_catalog
        .list_namespaces(Some(ns_apple.name()))
        .await
        .is_err());

    // Create namespaces
    fixture
        .rest_catalog
        .create_namespace(ns_apple.name(), ns_apple.properties().clone())
        .await
        .unwrap();

    // List namespace
    let nss = fixture
        .rest_catalog
        .list_namespaces(Some(&NamespaceIdent::from_strs(["a_a", "apple"]).unwrap()))
        .await
        .unwrap();
    assert!(nss.is_empty());
}
```

and run it return 
```
---- test_list_empty_namespace stdout ----
thread 'test_list_empty_namespace' panicked at crates/catalog/rest/tests/rest_catalog_test.rs:206:10:
called `Result::unwrap()` on an `Err` value: DataInvalid => Namespace does not exist: a_a%1Fapple

Context:
   type: NoSuchNamespaceException
   code: 404
   stack: org.apache.iceberg.exceptions.NoSuchNamespaceException: Namespace does not exist: a_a%1Fapple
        at org.apache.iceberg.jdbc.JdbcCatalog.listNamespaces(JdbcCatalog.java:338)
        at org.apache.iceberg.rest.CatalogHandlers.listNamespaces(CatalogHandlers.java:102)
        at org.apache.iceberg.rest.RESTCatalogAdapter.handleRequest(RESTCatalogAdapter.java:280)
        at org.apache.iceberg.rest.RESTCatalogAdapter.execute(RESTCatalogAdapter.java:444)
        at org.apache.iceberg.rest.RESTCatalogServlet.execute(RESTCatalogServlet.java:100)
        at org.apache.iceberg.rest.RESTCatalogServlet.doGet(RESTCatalogServlet.java:66)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:840)

...
```

### PR DESCRIPTION
**Pull request by liurenjie1024**
Close #433 

We should call `encode` method for namespace identifier in url.

### CODE REVIEW

File: crates/iceberg/src/catalog/mod.rs [hunk 1]
```diff
@@ -123,9 +122,9 @@ impl NamespaceIdent {
         Self::from_vec(iter.into_iter().map(|s| s.to_string()).collect())
     }
 
-    /// Returns url encoded format.
-    pub fn encode_in_url(&self) -> String {
-        encode(&self.as_ref().join("\u{1F}")).to_string()
+    /// Returns a string for used in url.
+    pub fn to_url_string(&self) -> String {
+        self.as_ref().join("\u{001f}")
```
Comment (Xuanwo) [inline crates/iceberg/src/catalog/mod.rs:127]: How about using `percent_encoding`?

**Comment by thexiay** [comment]
> cc @thexiay Would you take a look if this helps?

yes， it really helps!

**Review by thexiay — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]
Thanks!

**Review by Fokko — APPROVED** [review]
Thanks for working on this @liurenjie1024, and thanks @thexiay and @Xuanwo for the review!
