### PR TITLE
fix: return proper error rather than persisting error message on snapshot

### LINKED ISSUE #1957: V1 metadata parsing incorrectly accepts snapshots with both manifest-list and manifests.
### Apache Iceberg Rust version

None

### Describe the bug

For V1 snapshots, the spec requires that the manifests field must be omitted if manifest-list is present.

But the current V1 snapshot parsing incorrectly accepts this, and worse, stores an error message as the manifest-list value.

It looks like this bug may have been introduced during https://github.com/apache/iceberg-rust/pull/201/changes#diff-eee8bc669cc946bb5e92cd9d4759e49b89f5cbf4a6c0ab6741ba987b7bf8596eR287

I think updating that match arm to return an error instead of a string should fix the bug.

### To Reproduce

```rust
#[test]
fn test_v1_snapshot_with_both_manifest_list_and_manifests_is_spec_violation() {
    let metadata = r#"
    {
        "format-version": 1,
        "table-uuid": "d20125c8-7284-442c-9aea-15fee620737c",
        "location": "s3://bucket/test/location",
        "last-updated-ms": 1700000000000,
        "last-column-id": 1,
        "schema": {
            "type": "struct",
            "fields": [
                {"id": 1, "name": "x", "required": true, "type": "long"}
            ]
        },
        "partition-spec": [],
        "properties": {},
        "current-snapshot-id": 111111111,
        "snapshots": [
            {
                "snapshot-id": 111111111,
                "timestamp-ms": 1600000000000,
                "summary": {"operation": "append"},
                "manifest-list": "s3://bucket/metadata/snap-123.avro",
                "manifests": ["s3://bucket/metadata/manifest-1.avro"]
            }
        ]
    }
    "#;

    let result = serde_json::from_str::<TableMetadata>(metadata);
    assert!(
        result.is_ok(),
        "Parsing should fail for spec violation but currently succeeds"
    );
    // Expected behavior
    // assert!(result.is_err());

    let table_metadata = result.unwrap();
    let snapshot = table_metadata
        .snapshot_by_id(111111111)
        .expect("snapshot exists due to a bug");

    let manifest_list = snapshot.manifest_list();

    // The manifest_list incorrectly contains an error message
    assert_eq!(
        manifest_list,
        "Invalid v1 snapshot, when manifest list provided, manifest files should be omitted"
    );
}
```

### Expected behavior

Spec-violating metadata JSON should be rejected.

### Willingness to contribute

None

### PR DESCRIPTION
**Pull request by Standing-Man**
## Which issue does this PR close?

- Closes #1957.

## What changes are included in this PR?

Avoid storing error message on snapshot, return error instead.

## Are these changes tested?

Yes

### CODE REVIEW

**Comment by Standing-Man** [comment]
@CTTY and @yshcz ready to review.

File: crates/iceberg/src/spec/snapshot.rs [hunk 1]
```diff
@@ -408,9 +408,19 @@ pub(super) mod _serde {
                 timestamp_ms: v1.timestamp_ms,
                 manifest_list: match (v1.manifest_list, v1.manifests) {
                     (Some(file), None) => file,
-                    (Some(_), Some(_)) => "Invalid v1 snapshot, when manifest list provided, manifest files should be omitted".to_string(),
-                    (None, _) => "Unsupported v1 snapshot, only manifest list is supported".to_string()
-                   },
+                    (Some(_), Some(_)) => {
+                        return Err(Error::new(
+                            ErrorKind::Unexpected,
+                            "v1 snapshot invariant violated: manifest_list and manifests are both set",
```
Comment (CTTY) [inline crates/iceberg/src/spec/snapshot.rs]:
```suggestion
                            "Invalid v1 snapshot, when manifest list provided, manifest files should be omitted",
```
I think the original error message is more specific

File: crates/iceberg/src/spec/snapshot.rs [hunk 2]
```diff
@@ -408,9 +408,19 @@ pub(super) mod _serde {
...
+                        ));
+                    }
+                    (None, _) => {
+                        return Err(Error::new(
+                            ErrorKind::FeatureUnsupported,
+                            "v1 snapshot invariant violated: manifest_list is missing",
```
Comment (CTTY) [inline crates/iceberg/src/spec/snapshot.rs]:
```suggestion
                            "Unsupported v1 snapshot, only manifest list is supported",
```
Same here, the original message is more specific

File: crates/iceberg/src/spec/snapshot.rs [hunk 3]
```diff
@@ -408,9 +408,19 @@ pub(super) mod _serde {
                 timestamp_ms: v1.timestamp_ms,
                 manifest_list: match (v1.manifest_list, v1.manifests) {
                     (Some(file), None) => file,
-                    (Some(_), Some(_)) => "Invalid v1 snapshot, when manifest list provided, manifest files should be omitted".to_string(),
-                    (None, _) => "Unsupported v1 snapshot, only manifest list is supported".to_string()
-                   },
+                    (Some(_), Some(_)) => {
+                        return Err(Error::new(
+                            ErrorKind::Unexpected,
```
Comment (CTTY) [inline crates/iceberg/src/spec/snapshot.rs]:
```suggestion
                            ErrorKind::DataInvalid,
```
Referring to the v3 parsing and error handling logic [here](https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/spec/snapshot.rs#L349), `DataInvlid` seems more apporpriate

File: crates/iceberg/src/spec/snapshot.rs [hunk 4]
```diff
@@ -408,9 +408,19 @@ pub(super) mod _serde {
...
+                            "v1 snapshot invariant violated: manifest_list and manifests are both set",
+                        ));
+                    }
+                    (None, _) => {
+                        return Err(Error::new(
+                            ErrorKind::FeatureUnsupported,
```
Comment (CTTY) [inline crates/iceberg/src/spec/snapshot.rs]:
```suggestion
                            ErrorKind::DataInvalid,
```
Same here

File: crates/iceberg/src/spec/snapshot.rs [hunk 5]
```diff
@@ -604,6 +615,73 @@ mod tests {
...
+                "summary": {"operation": "append"},
+                "manifest-list": "s3://bucket/metadata/snap-123.avro",
+                "manifests": ["s3://bucket/metadata/manifest-1.avro"]
+            }
+        ]
+    }
+    "#;
+
+            let result = serde_json::from_str::<TableMetadata>(metadata);
+            assert!(result.is_err());
```
Comment (CTTY) [inline crates/iceberg/src/spec/snapshot.rs]: We should also check if the error has the correct error type/message. So other developers will know what we are testing here

File: crates/iceberg/src/spec/snapshot.rs [hunk 6]
```diff
@@ -604,6 +615,73 @@ mod tests {
...
+                "snapshot-id": 111111111,
+                "timestamp-ms": 1600000000000,
+                "summary": {"operation": "append"},
+                "manifests": ["s3://bucket/metadata/manifest-1.avro"]
+            }
+        ]
+    }
+    "#;
+            let result = serde_json::from_str::<TableMetadata>(metadata);
+            assert!(result.is_err());
```
Comment (CTTY) [inline crates/iceberg/src/spec/snapshot.rs]: Same here, we should also check if the error has the correct error type/message.

**Review by CTTY — CHANGES_REQUESTED** [review]
Hi @Standing-Man , thanks for the contribution! Looks good overall, I just have some minor feedbacks

File: crates/iceberg/src/spec/snapshot.rs (hunk 6 above)
Comment (Standing-Man) [reply crates/iceberg/src/spec/snapshot.rs]: In the new commit, I added a check to ensure the error message is correct, but I’m not sure this is the best approach. Currently, I just convert the error to a string and compare it.

Comment (CTTY) [reply crates/iceberg/src/spec/snapshot.rs]: The point is to help people understand what this test is about when reading code. String comparison should be fine. I think a more elegant way is
```rust
let result_missing_manifest_list = serde_json::from_str::<TableMetadata>(metadata);
assert!(result_missing_manifest_list.is_err());
```

**Review by CTTY — APPROVED** [review]
LGTM!
