### PR TITLE
fix: Interpret s3tables warehouse as table_location not metadata loca…

### LINKED ISSUE #2114: bug: Incorrect interpretation of S3 create tables warehouse field
### Apache Iceberg Rust version

0.6.0 (latest version)

### Describe the bug

It appears that s3 tables creation does  misinterprets the warehouse as metadata_location.

> When you create a table, Amazon S3 automatically generates a warehouse location for the table. This is a unique S3 location that stores objects associated with the table. The following example shows the format of a warehouse location:

```
s3://63a8e430-6e0b-46f5-k833abtwr6s8tmtsycedn8s4yc3xhuse1b--table-s3
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Willingness to contribute

Yes.

### PR DESCRIPTION
**Pull request by emkornfield**
## Which issue does this PR close?

AWS [Docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-tables-tables.html) state: 

> When you create a table, Amazon S3 automatically generates a warehouse location for the table. This is a unique S3 location that stores objects associated with the table. The following example shows the format of a warehouse location:

```
s3://63a8e430-6e0b-46f5-k833abtwr6s8tmtsycedn8s4yc3xhuse1b--table-s3
```

We were previously interpreting this as as a metadata location (i.e. the path to the metadata.json file), this changes the code use it as a table location.

- Closes #2114

## What changes are included in this PR?

Change how we construct the MetadataLocation object.

## Are these changes tested?

There never appears to have been a test, and I don't have an AWS account to verify this. Note the test was initially developed by Claude Code and refined by me.

### CODE REVIEW

**Comment by emkornfield** [comment]
@CTTY @flaneur2020 thoughs on this change?

**Comment by emkornfield** [comment]
> Hi @emkornfield , this fix makes sense to me. Maybe we can add a test to cover it?

I'm not really sure what a test would do here.  we can try to mock the service with the expected value, but I'm not sure that gives us much confidence?  If we think mocking does add value, I can look into doing it.

**Comment by emkornfield** [comment]
I pinged on slack to see if anybody has ideas on a Fake or integration tests so this can be done properly.

**Comment by emkornfield** [comment]
There was no response on slack, I've updated to have a mocked test.  CC @CTTY

File: crates/catalog/s3tables/src/catalog.rs [hunk 1]
```diff
@@ -1123,4 +1129,129 @@ mod tests {
...
+
+        TableCreation::builder()
+            .name(table_name.to_string())
+            .properties(HashMap::new())
+            .schema(schema)
+            .build()
+    }
+
+    #[tokio::test]
+    async fn test_create_table_with_mocked_client() {
```
Comment (blackmwk) [inline crates/catalog/s3tables/src/catalog.rs]: I think this has been covered by other tests, so we don't need this? Mocked response may not help much.

Comment (emkornfield) [reply crates/catalog/s3tables/src/catalog.rs]: @blackmwk I agree Mocked response doesn't help much.  The problem is:
1.  These tests don't appear to be run in CI (at least I could find anything setting  TABLE_BUCKET_ARN but might be looking in the wrong place) which makes me think the tests would just be skipped silently.
2. I don't have an AWS account to test this (and I'm a little surprised tests pass as is if we had one).

I'll remove the tests for now (in a separate commit in case we decide to keep them).

Comment (emkornfield) [reply crates/catalog/s3tables/src/catalog.rs]: OK, reverted the test. Thanks for the review @blackmwk
