### PR TITLE
fix: Serialize `split_offsets` as null when empty

### LINKED ISSUE #1897: `split_offsets` is not serialised as `null` when empty
When a `DataFile` is built through the derived builder (`DataFileBuilder`) and no `split_offsets` are given, this is still serialised as `[]` instead of `null`.

E.g. converting the Avro file to JSON it looks something like this:

```json
   ...
    "split_offsets": {
      "array": []
    },
```

I suspect this is because the value within the `DataFile` is a `Vec<i64>` instead of an `Option<Vec<i64>>`, so we get an empty `Vec` instead of nothing. 

I _think_ this `Option` is the correct approach because the spec also states that `split_offsets` are optional and it looks like they're [optional in the Java implementation](https://github.com/apache/iceberg/blob/16e84356dae1975fa04d8c3ecce30a90df18ca9f/api/src/main/java/org/apache/iceberg/DataFile.java#L89-L91) too.

### PR DESCRIPTION
**Pull request by AndreaBozzo**
- Change `split_offsets` in `DataFile` from `Vec<i64>` to `Option<Vec<i64>>`
- Empty values now serialize as `null` instead of `[]`
- Aligns with Iceberg spec (field is optional)

Closes #1897

### CODE REVIEW

**Comment by AndreaBozzo** [comment]
The unit tests (smol) workflow fails, but it looks unrelated to my changes

```
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: 1 target failed:
    `-p iceberg-catalog-glue --test glue_catalog_test`
Error: Process completed with exit code 101
```

**Comment by lgingerich** [comment]
Note: I'm a new reviewer/contributor in this repo, but trying to help out as PR reviews seems to be a heavily requested area of needed help.

I've reviewed these changes and looked for potential missed needed updates. All looks good to me!

Agreed that the failing test looks unrelated. I ran `cargo test -p iceberg-catalog-glue --test glue_catalog_test` locally on your branch and it passed successfully.

Including a pic and link for the Iceberg spec for any other reviewers:

Image from the [Iceberg spec](https://iceberg.apache.org/spec/#manifest-entry-fields)
image

**Comment by AndreaBozzo** [comment]
Thanks for your feedback @lgingerich !

File: bindings/python/src/data_file.rs [hunk 1]
```diff
@@ -143,8 +143,8 @@ impl PyDataFile {
     }
 
     #[getter]
-    fn split_offsets(&self) -> &[i64] {
-        self.inner.split_offsets()
+    fn split_offsets(&self) -> Option<Vec<i64>> {
```
Comment (liurenjie1024) [inline bindings/python/src/data_file.rs]:
```suggestion
    fn split_offsets(&self) -> Option<&[i64]> {
```

We don't need to collect into vector.

**Comment by AndreaBozzo** [comment]
> Thanks @AndreaBozzo for this pr, just one comment.

Thanks for your review @liurenjie1024 , i addressed your comment in the last commit [8ba3d58](https://github.com/apache/iceberg-rust/pull/1906/commits/8ba3d58dcc26c4aa0e4051cd708301e92d6efbd2)

**Comment by AndreaBozzo** [comment]
> Thanks @AndreaBozzo for this pr!

Thanks to you! Have a nice day
