### PR TITLE
fix: SqlCatalogBuilder does not save supplied name in SqlCatalogConfig before initializing SqlCatalog

### LINKED ISSUE #1990: SQL catalog ignores name supplied
### Apache Iceberg Rust version

0.6.0 (latest version)

### Describe the bug

SQL catalog's load method just ignores name argument passed and always uses default value (""). This means when opening existing catalog, it fails to find namespaces or incorrectly finds namespaces.

Value is assigned in below line but catalog config is never updated.
https://github.com/apache/iceberg-rust/blob/main/crates/catalog/sql/src/catalog.rs#L139

### To Reproduce

_No response_

### Expected behavior

Name passed to load method should be used to initialize config correctly.

### Willingness to contribute

I can contribute a fix for this bug independently

### PR DESCRIPTION
**Pull request by brodiealexander**
There hasn't been any movement on #1991 for a while so I wanted to see if I could help out. I'm not sure what the correct way of trying to continue where another PR left off is, so please let me know if there is a better way of going about this! 

## Which issue does this PR close?

Closes #1990
Refer to PR #1991

## What changes are included in this PR?

Changes to SqlCatalogBuilder from #1991 are included but the new_sql_catalog function has been refactored to accept an optional name parameter. Relevant tests have been adjusted accordingly.

## Are these changes tested?

Yes, refer to #1991 for cornerwings' added test. I've run the local `make test` and everything seems to check out. 

Thanks!
    Brodie

### CODE REVIEW

File: crates/catalog/sql/src/catalog.rs [hunk 1]
```diff
@@ -1004,7 +1008,41 @@ mod tests {
         HashMap::from([("exists".to_string(), "true".to_string())])
     }
 
-    async fn new_sql_catalog(warehouse_location: String) -> impl Catalog {
+    // async fn new_sql_catalog_with_name(
```
Comment (liurenjie1024) [inline crates/catalog/sql/src/catalog.rs]: Remove them if no longer used.

File: crates/catalog/sql/src/catalog.rs [hunk 2]
```diff
@@ -149,6 +147,12 @@ impl CatalogBuilder for SqlCatalogBuilder {
             self.0.warehouse_location = warehouse_location;
         }
 
+        let name = name.into();
+        let valid_name = !name.trim().is_empty();
+        if valid_name {
```
Comment (liurenjie1024) [inline crates/catalog/sql/src/catalog.rs]: Why not just return error here if no valid?

Comment (brodiealexander) [reply crates/catalog/sql/src/catalog.rs]: It actually would return an error in the later lines in the async move {} block, but I agree that it's unclear as it's presented here. I'll move it around to make the flow a bit clearer.

File: crates/catalog/sql/src/catalog.rs (hunk 1 above)
Comment (brodiealexander) [reply crates/catalog/sql/src/catalog.rs]: Yes! Sorry, I had to re-do these changes like three times before I could figure out how to include credit for @cornerwings work.
