### PR TITLE
fix: Use CatalogCommitConflicts for TableRequirement

### LINKED ISSUE #1531: TableRequirement check failure should return CatalogCommitConflicts
### Apache Iceberg Rust version

None

### Describe the bug

As title, requirement checks like [here](https://github.com/apache/iceberg-rust/blob/dfbab0da0000fe3f16e793415aeef642e529acee/crates/iceberg/src/catalog/mod.rs#L600) should return CatalogCommitConflicts, otherwise it will be non-retryable by default

### To Reproduce

_No response_

### Expected behavior

_No response_

### Willingness to contribute

I can contribute a fix for this bug independently

### PR DESCRIPTION
**Pull request by CTTY**
## Which issue does this PR close?

- Closes #1531 

## What changes are included in this PR?

- Use `ErrorKind::CatalogCommitConflicts` for `TableRequirement::check`
- When metadata is None, returns `ErrorKind::TableNotFound`
- Minor trimmings

## Are these changes tested?
No

### CODE REVIEW

File: crates/iceberg/src/error.rs [hunk 1]
```diff
@@ -232,7 +234,7 @@ impl Error {
             // internally. It's zero cost if backtrace is disabled.
             backtrace: Backtrace::capture(),
 
-            retryable: false,
+            retryable: kind == ErrorKind::CatalogCommitConflicts,
```
Comment (liurenjie1024) [inline crates/iceberg/src/error.rs]: This is odd to me, I would expect explicit call to change the `retryable` property.

Comment (CTTY) [reply crates/iceberg/src/error.rs]: Hmm I don't have a strong opinion on this, was just thinking it will be more convenient like this. Will fix this
