### PR TITLE
fix(metadata): export iceberg schema in manifests table

### LINKED ISSUE #868: Manifests table scan should return iceberg schema rather arrow schema
I think we should return iceberg schema here, and user could easily convert it to arrow schema.

_Originally posted by @liurenjie1024 in https://github.com/apache/iceberg-rust/pull/861#discussion_r1901601914_

### PR DESCRIPTION
**Pull request by flaneur2020**
fixes #868

the field annotation numbers are referenced from the java implementation: https://github.com/apache/iceberg/blob/8a70fe0ff5f241aec8856f8091c77fdce35ad256/core/src/main/java/org/apache/iceberg/ManifestsTable.java

### CODE REVIEW

File: crates/iceberg/src/metadata_scan.rs [hunk 1]
```diff
@@ -134,44 +137,122 @@ pub struct ManifestsTable<'a> {
...
+            schema.field_with_name("partition_summaries")?.data_type()
+        {
+            if let DataType::Struct(fields) = list_type.data_type() {
+                fields.to_vec()
+            } else {
+                unreachable!()
+            }
+        } else {
+            unreachable!()
+        };
```
Comment (flaneur2020) [inline crates/iceberg/src/metadata_scan.rs:253]: very ugly here 😲

File: crates/iceberg/src/metadata_scan.rs [hunk 2]
```diff
@@ -183,21 +264,21 @@ impl<'a> ManifestsTable<'a> {
...
         ))
-        .with_field(Arc::new(Field::new_struct(
-            "item",
-            self.partition_summary_fields(),
-            false,
-        )));
+        .with_field(Arc::new(
+            Field::new_struct("item", partition_summary_fields, false).with_metadata(
+                HashMap::from([("PARQUET:field_id".to_string(), "9".to_string())]),
+            ),
```
Comment (flaneur2020) [inline crates/iceberg/src/metadata_scan.rs:273]: also ugly here 😲

**Review by Xuanwo — APPROVED** [review]
Thank you @flaneur2020 for working on this, looks good.
